/*
 *  Software Platform Generated File
 *  --------------------------------
 */

#ifndef _SWP_PER_STM32F4XX_I2S_CFG_INSTANCE_H
#define _SWP_PER_STM32F4XX_I2S_CFG_INSTANCE_H

#include "per_stm32f4xx_i2s_cfg.h"

#include <stdint.h>
#include <stddef.h>
#include <stm32f4xx.h>

#define PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_RX_DMA1_STREAM0  DMA1_Stream0
#define PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_RX_DMA1_STREAM3  DMA1_Stream3

#define PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_TX_DMA1_STREAM4  DMA1_Stream4
#define PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_TX_DMA1_STREAM5  DMA1_Stream5

#define PER_STM32F4XX_I2S_INSTANCE_BASEADDRESS_MIN  0x40003C00
#define PER_STM32F4XX_I2S_INSTANCE_BASEADDRESS_MAX  0x40003C00

#define PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_RX_DMA1_STREAM0_USED  1
#define PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_RX_DMA1_STREAM3_USED  0
#define PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_RX_OPTIONS_USED  1
#define PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_RX_MIN  PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_RX_DMA1_STREAM0
#define PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_RX_MAX  PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_RX_DMA1_STREAM0

#define PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_TX_DMA1_STREAM4_USED  0
#define PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_TX_DMA1_STREAM5_USED  1
#define PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_TX_OPTIONS_USED  1
#define PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_TX_MIN  PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_TX_DMA1_STREAM5
#define PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_TX_MAX  PER_STM32F4XX_I2S_INSTANCE_DMA_STREAM_TX_DMA1_STREAM5


// instance data
typedef struct
{
    int instance_id;
        uint32_t baseaddress;
        void (*pinconfig)(void);
        int8_t interrupt0;
        DMA_Stream_TypeDef * dma_stream_rx;
        DMA_Stream_TypeDef * dma_stream_tx;
} per_stm32f4xx_i2s_cfg_instance_t;

extern const per_stm32f4xx_i2s_cfg_instance_t per_stm32f4xx_i2s_instance_table[]; 

#endif /* _SWP_PER_STM32F4XX_I2S_CFG_INSTANCE_H */
