version: 2

# This is an example .goreleaser.yaml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
# https://goreleaser.com/customization/#Builds

builds:
  #
  # 1) Universal 64-bit build for ALL platforms:
  #    - windows/amd64
  #    - windows/arm64
  #    - linux/amd64
  #    - linux/arm64
  #    - darwin/amd64
  #    - darwin/arm64
  #
  - id: trice-64bit   # ID of the build. Defaults to the project name.
    main: ./cmd/trice # Path to main.go file or main package. Default is `.`.
    binary: trice     # Binary name. Can be a path (e.g. `bin/app`) to wrap the binary in a directory. Default is the name of the project directory.
    dir: .            # Path to project's (sub)directory containing Go code. This is the working directory for the Go build command(s). Default is `.`.
    goos:             # GOOS list to build for. For more info refer to: https://golang.org/doc/install/source#environment.
      - windows
      - linux
      - darwin
    goarch:           # GOARCH to build for. For more info refer to: https://golang.org/doc/install/source#environment. Defaults are 386 and amd64.
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:          # You don't need to set this because GoReleaser sets the three ldflags by default anyway.
      - >-            # But sometimes it's better to be explicit, especially if you want to expand later (e.g., builtBy):
        -s -w
        -X main.version={{ .Version }}
        -X main.commit={{ .Commit }}
        -X main.date={{ .Date }}
        -X main.builtBy=goreleaser
  
  #
  # 2) 32-bit build ONLY for Windows and Linux (NO darwin/386)
  #
  - id: trice-32bit   # ID of the build. Defaults to the project name.
    main: ./cmd/trice # Path to main.go file or main package. Default is `.`.
    binary: trice     # Binary name. Can be a path (e.g. `bin/app`) to wrap the binary in a directory. Default is the name of the project directory.
    dir: .            # Path to project's (sub)directory containing Go code. This is the working directory for the Go build command(s). Default is `.`.
    goos:             # GOOS list to build for. For more info refer to: https://golang.org/doc/install/source#environment.
      - windows
      - linux         # <— darwin deliberately omitted
    goarch:           # GOARCH to build for. For more info refer to: https://golang.org/doc/install/source#environment. Defaults are 386 and amd64.
      - 386           # <— 32-bit x86 only here
    env:
      - CGO_ENABLED=0
    ldflags:          # You don't need to set this because GoReleaser sets the three ldflags by default anyway.
      - >-            # But sometimes it's better to be explicit, especially if you want to expand later (e.g., builtBy):
        -s -w
        -X main.version={{ .Version }}
        -X main.commit={{ .Commit }}
        -X main.date={{ .Date }}
        -X main.builtBy=goreleaser

  #
  # 3) ARMv6/v7 Linux builds (embedded targets)
  #
  - id: trice-arm32   # ID of the build. Defaults to the project name.
    main: ./cmd/trice # Path to main.go file or main package. Default is `.`.
    binary: trice     # Binary name. Can be a path (e.g. `bin/app`) to wrap the binary in a directory. Default is the name of the project directory.
    dir: .            # Path to project's (sub)directory containing Go code. This is the working directory for the Go build command(s). Default is `.`.
    goos:             # GOOS list to build for. For more info refer to: https://golang.org/doc/install/source#environment.
      - linux
    goarch:           # GOARCH to build for. For more info refer to: https://golang.org/doc/install/source#environment. Defaults are 386 and amd64.
      - arm
    goarm:            # GOARM to build for when GOARCH is arm. (only Linux). For more info refer to: https://golang.org/doc/install/source#environment. # Default is only 6.
      - 6
      - 7
    env:              # Custom environment variables to be set during the builds. # Default is empty.
      - CGO_ENABLED=0
    ldflags:          # You don't need to set this because GoReleaser sets the three ldflags by default anyway.
      - >-            # But sometimes it's better to be explicit, especially if you want to expand later (e.g., builtBy):
        -s -w
        -X main.version={{ .Version }}
        -X main.commit={{ .Commit }}
        -X main.date={{ .Date }}
        -X main.builtBy=goreleaser

checksum:
  # You can change the name of the checksums file.
  # Default is `{{ .ProjectName }}_{{ .Version }}_checksums.txt`.
  #name_template: "{{ .ProjectName }}_checksums.txt"
  #name_template: 'checksums.txt'
  # Algorithm to be used.
  # Accepted options are sha256, sha512, sha1, crc32, md5, sha224 and sha384.
  # Default is sha256.
  #algorithm: sha256

snapshot:
  # Allows you to change the name of the generated snapshot
  #
  # Note that some pipes require this to be semantic version compliant (nfpm,
  # for example).
  #
  # Default is `{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}`.
  #name_template: 1.2.3-SNAPSHOT-{{.Commit}}
  #name_template: "{{ .Tag }}-next"
  #name_template: "{{ incpatch .Version }}-next"

# You can customize how the changelog is generated using the changelog section in the config file
changelog:
  # set it to true if you wish to skip the changelog generation
  #skip: false
  # could either be asc, desc or empty
  # Default is empty
  sort: asc
  filters:
    # commit messages matching the regexp listed here will be removed from
    # the changelog
    # Default is empty
    exclude:
      - '^typo$'
      - '^minor$'
      - '^update$'
      - '^wip$'

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

archives:
  - 
    #rlcp: true

    #- format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    #name_template: >-
    #  {{ .ProjectName }}_
    #  {{- title .Os }}_
    #  {{- if eq .Arch "amd64" }}x86_64
    #  {{- else if eq .Arch "386" }}i386
    #  {{- else }}{{ .Arch }}
    #  {{ end }}
    #  {{- if .Arm }}v{{ .Arm }}{{ end }}
    # name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}"

    # Set to true, if you want all files in the archive to be in a single directory.
    # If set to true, and you extract the archive 'goreleaser_Linux_arm64.tar.gz',
    # you get a folder 'goreleaser_Linux_arm64'.
    # If set to false, all files are extracted separately.
    # You can also set it to a custom folder name (templating is supported).
    # Default is false.
    wrap_in_directory: true
    
    # Archive format. Valid options are `tar.gz`, `gz`, `zip` and `binary`.
    # If format is `binary`, no archives are created and the binaries are instead
    # uploaded directly.
    # Default is `tar.gz`.
    formats:
      - tar.gz
    
    # use zip for windows archives
    # Can be used to change the archive formats for specific GOOSs.
    # Most common use case is to archive as zip on Windows.
    # Default is empty.
    format_overrides:
    - goos: windows
      formats: [ 'zip' ]

    # Additional files/globs you want to add to the archive.
    # Defaults are any files matching `LICENCE*`, `LICENSE*`,
    # `README*` and `CHANGELOG*` (case-insensitive).
    # This list excludes the Go sources and git related files but includes the target source code.
    files:
      - "**/launch.json"
      - "**/settings.json"
      - "**/c_cpp_properties.json"
      - "**/test*.json"
      - "**/ReadMe.md"
      - "**/*.jpg"
    # - "**/*.JPG"
    # - "**/*.jpeg"
    # - "**/*.JPEG"
      - "**/*.png"
      - "**/*.PNG"
      - "**/*.gif"
    # - "**/*.GIF"
    # - "**/*.svg"
    # - "**/*.SVG"
    # - "**/*.html"
    # - "**/*.pdf"
      - "**/*.txt"
    # - "**/*.yml"
      - "AUTHORS.md"
      - "CHANGELOG.md"
      - "LICENSE.md"
      - "**/LICENSE"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "README.md"
      - _test/**/*.c
      - _test/**/*.h
      - _test/**/*.go
    # - .code_snippets/*
    # - .github/*
    # - .idea/*
    # - cmd/*
    # - dist/*
      - docs/*.pdf
      - docs/*.md
      - docs/*.html
      - examples/**/.cortex*.json
      - examples/**/*.sh
      - examples/**/*.c
      - examples/**/*.h
      - examples/**/*.s
      - examples/**/*.ld
      - examples/**/*.svd
      - examples/**/*.mak
      - examples/**/Makefile
      - examples/**/Makefile.*
      - examples/**/*.ioc
      - examples/**/*.code-workspace
      - examples/**/*.jflash
      - examples/**/*.cfg
      - examples/*.sh
    # - internal/*
    # - pkg/*
      - src/*.c
      - src/*.h
    # - super-linter.report
      - third_party/**/*.zip
      - third_party/*.zip
      - _config.yml
      - _test
      - .clang-format
      - .clang-format-ignore
      - .editorconfig
    # - .gitattributes
    # - .github
    # - .gitignore
      - .goreleaser.yaml
    # - .idea
      - .markdownlinkcheck.json
      - .markdownlint.yaml
      - .markdownlintignore
      - .vscode
      - build_environment.sh
      - buildTriceTool.sh
      - clean-dsstore.sh
    # - build.sh
      - clang-format.sh
      - clean-dsstore.sh
      - demoLI.json
      - demoTIL.json
      - format-dumeng-toc.sh
    # - gitAddWorktreeFromGitLogLineData.sh
    # - gitAddWorktreesBetween.sh
    # - gitLogWithBranches.sh
    # - go.mod
    # - go.sum
    # - index.md
    # - lychee.toml
      - renewIDs_in_examples_and_refresh_test_folder.sh
      - testAll.log
    # - testAll.sh
      - trice_cleanIDs_in_examples_and_test_folder.sh
      - trice_environment.sh
      - trice_insertIDs_in_examples_and_test_folder.sh
