//! \file til.json.c
//! ///////////////////////////////////////////////////////////////////////////

//! generated code - do not edit!

#include "til.json.h"

//! triceFormatStringList contains all trice format strings together with id and parameter information.
const triceFormatStringList_t triceFormatStringList[] = {
	// format-string,                                                                     id, dataLength, bitWidth,
    { "rd:TRICE64_1 line %o (%%o)\n",                                                     2590,   8, 64 },
    { "ATT:attention   message, SysTick is %6u\n",                                        3908,   4, 32 },
    { "tst:TRICE64_1 %u\n",                                                               3959,   8, 64 },
    { "1/11 = %g\n",                                                                      5757,   4, 32 },
    { "rd:TRICE64 %d, %d, %d, %d, %d, %d, %d\n",                                          2434,  56, 64 },
    { "tst:TRICE16_2 %d %d\n",                                                            3091,   4, 16 },
    { "tst:TRICE64_2 %u %u\n",                                                            4034,  16, 64 },
    { "wrn:TRICE_UARTB Send Break Flag is set\n",                                         3907,   0, 32 },
    { "wrn:TRICE_UARTA Send Break Flag is set\n",                                         7928,   0, 32 },
    { "s:     CGO-TEST     TRICE_MODE %3u     \n",                                        4305,   1,  8 },
    { "TIME:blue+i:blue+h\n",                                                             2039,   0, 32 },
    { "info:cyan+b:default+h\n",                                                          6972,   0, 32 },
    { "e:7",                                                                              4132,   0, 32 },
    { "tst:TRICE32 %d %d %d %d %d\n",                                                     3178,  20, 32 },
    { "wrn:TRICE_UARTA Auto-Baud Rate Flag is set\n",                                     5656,   0, 32 },
    { "w:B",                                                                              2917,   0, 32 },
    { "WARNING:11+i:red\n",                                                               2831,   0, 32 },
    { "rd:TRICE32 %d, %d, %d\n",                                                          3397,  12, 32 },
    { "rd:TRICE8 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                       1093,  12,  8 },
    { "rd:TRICE16 %p, %p, %p, %p, %p, %p, %p, %p\n",                                      3125,  16, 16 },
    { "rd:TRICE float %-9.f (%%9.f)\n",                                                   5119,   0, 32 },
    { "rd:TRICE32 float %f (%%f)\n",                                                      5737,   4, 32 },
    { "diag:yellow+i:default+h\n",                                                        1929,   0, 32 },
    { "rd:TRICE16 %X, %X, %X, %X, %X, %X, %X, %X, %X\n",                                  6977,  18, 16 },
    { "sig:Various ranges and formats\n",                                                 3487,   0, 32 },
    { "rd:TRICE32 float %e (%%e)\n",                                                      2398,   4, 32 },
    { "INFO:cyan+b:default+h\n",                                                          1327,   0, 32 },
    { "sig:TRICE with 1 to 12 values\n",                                                  6182,   0, 32 },
    { "rd: +15 	%+d 	Always show sign\n",                                                 7801,   0, 32 },
    { "rd: ␣␣café 		%6s 		Width 6, right justify\n",                                 6473,  -1,  8 },
    { "rd:TRICE32 int %d, float %f (%%f), %08x, %032b\n",                                 7026,  16, 32 },
    { "--------------------------------------------------\n",                             7158,   0, 32 },
    { "receive:black+h:black\n",                                                          2807,   0, 32 },
    { "rd:TRICE64 %d, %d, %d, %d, %d\n",                                                  6310,  40, 64 },
    { "notice:TRICE64_F example:",                                                        7286,   0, 32 },
    { "att:...done\n",                                                                    7778,   0, 32 },
    { "tst:TRICE32_10 %d %d %d %d %d %d %d %d %d %d\n",                                   2414,  40, 32 },
    { "rd:TRICE32_1 %d\n",                                                                6922,   4, 32 },
    { "rd:TRICE float %9.f (%%9.f)\n",                                                    1538,   4, 32 },
    { "rd:TRICE32 float %F (%%F)\n",                                                      6132,   4, 32 },
    { "isr:TRICE isr message, SysTick is %6d\n",                                          2113,   4, 32 },
    { "tim:TRICE --------------------------------------------------\n",                   7832,   0, 32 },
    { "tst:TRICE32_4  %d %d %d %d\n",                                                     1499,  16, 32 },
    { "wrn:TRICE_UARTA Character Match Flag is set\n",                                    1222,   0, 32 },
    { "wr:TRICE_UARTB Transmission Complete Flag is set\n",                               5199,   0, 32 },
    { "sig:Some time measurements\n",                                                     5683,   0, 32 },
    { "rd:TRICE8_10 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                            4608,  10,  8 },
    { "rd:TRICE64_11 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                       3679,  88, 64 },
    { "--------------------------------------------------\n",                             7666,   0, 32 },
    { "rd:TRICE32 float %g (%%g)\n",                                                      7337,   4, 32 },
    { "s:                                          \n",                                   6668,   0, 32 },
    { "rd:TRICE8 %d\n",                                                                   4777,   1,  8 },
    { "ERR:error       message, SysTick is %6u\n",                                        1516,   4, 32 },
    { "tst:TRICE8_5  %d %d %d %d %d\n",                                                   3630,   5,  8 },
    { "tst:TRICE64_3  %d %d %d\n",                                                        5366,  24, 64 },
    { "rd: ␣␣123.46		%8.2f 	%%8.2f Width 8, precision 2\n",                           4504,   8, 64 },
    { "tst:TRICE8_12 %d %d %d %d %d %d %d %d %d %d %d %d\n",                              6506,  12,  8 },
    { "err:TRICE_UARTB Noise error detected Flag is set\n",                               2229,   0, 32 },
    { "tst:TRICE8_2  %d %d\n",                                                            5600,   2,  8 },
    { "\n",                                                                               5383,   0, 32 },
    { "notice:TRICE64_B example:",                                                        5782,   0, 32 },
    { "s:                                          \n",                                   2029,   0, 32 },
    { "tim:TRICE --------------------------------------------------\n",                   3506,   0, 32 },
    { "sig:TRICE64 with 1 to 12 values\n",                                                4843,   0, 32 },
    { "rd:TRICE float %f (%%f)\n",                                                        4432,   4, 32 },
    { "rd:TRICE64 double %f (%%f), aDouble(y)\n",                                         7252,   8, 64 },
    { "rd:TRICE64 int %d, double %f (%%f), %016x, %064b\n",                               4801,  32, 64 },
    { "rd:TRICE8 line %b (%%b ,-1)\n",                                                    4235,   1,  8 },
    { "dbg:len=%u:",                                                                      1439,   4, 32 },
    { "rd:TRICE16 %d, %d, %d, %d, %d, %d, %d, %d\n",                                      1036,  16, 16 },
    { "rd: f 	%x 	Base 16, lowercase\n",                                                  2570,   4, 32 },
    { "tst:TRICE32_12 %t %b %x %X %d %u %o %O %p %e %f %g\n",                             4629,  48, 32 },
    { "rd:TRICE float %9.6f (%%9.6f)\n",                                                  6213,   4, 32 },
    { "rd:TRICE64 double %F (%%F), aDouble(y)\n",                                         2309,   8, 64 },
    { "msg:%s\n",                                                                         4770,  -2,  8 },
    { "error:11:red\n",                                                                   7793,   0, 32 },
    { "dbg:\tHi!\n",                                                                      2818,   0, 32 },
    { "WR:write        message, SysTick is %6u\n",                                        7021,   4, 32 },
    { "tst:TRICE32_3 %u %u %u\n",                                                         3841,  12, 32 },
    { "time:i",                                                                           4116,   0, 32 },
    { "rd:TRICE float %-9.f (%%9.f)\n",                                                   6313,   0, 32 },
    { "tst:TRICE32_4 %u %u %u %u\n",                                                      7625,  16, 32 },
    { "tst:TRICE8   %t %b %x %X %d %u %o %O %p\n",                                        4744,   9,  8 },
    { "rd:TRICE line %t (%%t -1)\n",                                                      5876,   4, 32 },
    { "att:Single Trice Stack buf size:%4u",                                              5332,   4, 32 },
    { "EMERGENCY:red+i:blue\n",                                                           1977,   0, 32 },
    { "tst:TRICE32_3 %x %x %x\n",                                                         3456,  12, 32 },
    { "err:TRICE_UARTA Receiver Time Out Flag is set\n",                                  7600,   0, 32 },
    { "rd:TRICE16_2 %d, %d\n",                                                            4552,   4, 16 },
    { "rd:TRICE16_11 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                       1196,  22, 16 },
    { "tst:TRICE8_2 %d %d\n",                                                             1765,   2,  8 },
    { "tst:TRICE16 %d %d %d %d %d\n",                                                     6936,  10, 16 },
    { "isr:TRICE isr message, SysTick is %6d\n",                                          2052,   4, 32 },
    { "err:TRICE_UARTA OverRun Error Flag is set\n",                                      4091,   0, 32 },
    { "rd:TRICE16 %d, %d, %d, %d\n",                                                      4243,   8, 16 },
    { "tst:TRICE16_11 %d %d %d %d %d %d %d %d %d %d %d\n",                                5743,  22, 16 },
    { "tst:TRICE64 %d\n",                                                                 6544,   8, 64 },
    { "rd:TRICE16_1 line %o (%%o -1)\n",                                                  4277,   2, 16 },
    { "rd:TRICE64_1 line %x (%%x)\n",                                                     2778,   8, 64 },
    { "rd:TRICE16 %p, %p, %p, %p, %p, %p, %p, %p, %p, %p\n",                              7559,  20, 16 },
    { "tst:TRICE16 %d\n",                                                                 3808,   2, 16 },
    { "rd:TRICE line %F (%%F)\n",                                                         3291,   4, 32 },
    { "rd:TRICE64 line %G (%%G)\n",                                                       3164,   8, 64 },
    { "tst:TRICE32 %d %d %d %d %d %d %d %d %d %d %d %d\n",                                7701,  48, 32 },
    { "wrn:TRICE_UARTB Receive Wake Up from mute mode Flag is set\n",                     7523,   0, 32 },
    { "s:                                          \n",                                   4245,   0, 32 },
    { "rd:TRICE64 double %G (%%G), aDouble(y)\n",                                         3402,   8, 64 },
    { "tst:TRICE8 %d %d %d\n",                                                            1360,   3,  8 },
    { "rd:TRICE float %9f (%%9f)\n",                                                      2812,   4, 32 },
    { "notice:TRICE_B example: ",                                                         7214,   0, 32 },
    { "tst:TRICE8_7 %d %d %d %d %d %d %d\n",                                              4497,   7,  8 },
    { "tst:TRICE16 %d %d %d %d %d %d %d %d %d %d\n",                                      5295,  20, 16 },
    { "WARNING:USARTq OverRun Error Flag is set!\n",                                      7108,   0, 32 },
    { "msg:x = %g = %d.%03d, %d.%03d\n",                                                  4314,  20, 32 },
    { "rd:TRICE64 %d, %d\n",                                                              1524,  16, 64 },
    { "rd:TRICE8_12 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                    4859,  12,  8 },
    { "rd:TRICE32 %d, %d, %d, %d, %d, %d\n",                                              5320,  24, 32 },
    { "e:A",                                                                              4159,   0, 32 },
    { "rd: A 	%c 	Character\n",                                                           7669,   4, 32 },
    { "s:                                          \n",                                   6366,   0, 32 },
    { "err:TRICE_UARTB Framing Error Flag is set\n",                                      5074,   0, 32 },
    { "rd:TRICE16 %p, %p, %p, %p\n",                                                      1822,   8, 16 },
    { "rd:TRICE line %o (%%o)\n",                                                         2606,   4, 32 },
    { "notice:TRICE8_F example:",                                                         3434,   0, 32 },
    { "sig:TRICE_n with 1 to 12 values\n",                                                2330,   0, 32 },
    { "rd:TRICE32_2 %d, %d\n",                                                            6409,   8, 32 },
    { "m:123\n",                                                                          1893,   0, 32 },
    { "rd:TRICE16 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                      6891,  24, 16 },
    { "tst:TRICE8_1 %d\n",                                                                4327,   1,  8 },
    { "notice:TRICE16_B example:",                                                        4315,   0, 32 },
    { "rd:TRICE8 %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                                   1273,   9,  8 },
    { "rd:TRICE16 %d, %d, %d\n",                                                          3774,   6, 16 },
    { "s:     NUCLEO-G071RB     TRICE_MODE %3u     \n",                                   2126,   1,  8 },
    { "\n",                                                                               7104,   0, 32 },
    { "WARNING:USARTq OverRun Error Flag is set!\n",                                      7229,   0, 32 },
    { "s:     ",                                                                          4604,   0, 32 },
    { "verbose:blue:default\n",                                                           3641,   0, 32 },
    { "rd:TRICE16 %d\n",                                                                  3404,   2, 16 },
    { "tst:TRICE32 %%10d ->     %10d     %10d     %10d    %10x\n",                        2810,  16, 32 },
    { "dbg:len=%u:",                                                                      7741,   4, 32 },
    { "att:positive float & double in variants\n",                                        3392,   0, 32 },
    { "fatal:magenta+b:red\n",                                                            1322,   0, 32 },
    { "rd:TRICE float %.9f (%%.9f)\n",                                                    7782,   4, 32 },
    { "rd:TRICE64 int %d, double %f (%%f), %016x, %064b\n",                               3987,  32, 64 },
    { "tim:TRICE STOP time message\n",                                                    2595,   0, 32 },
    { "tst:TRICE32    %t %b %x %X %d %u %o %O %p %e %f %g\n",                             5141,  48, 32 },
    { "rd:TRICE32_1 line %d\n",                                                           3885,   4, 32 },
    { "sig:TRICE32 with 1 to 12 values\n",                                                3067,   0, 32 },
    { "msg: messge = %08x %08x %08x %08x %08x %08x\n",                                    2186,  24, 32 },
    { "tst:TRICE8_2 %u %u\n",                                                             2033,   2,  8 },
    { "sig:Float (indent, precision, scientific notation)\n",                             4115,   0, 32 },
    { "rd:TRICE float %+9.f (%%9.f)\n",                                                   4261,   0, 32 },
    { "tim:TRICE --------------------------------------------------\n",                   4854,   0, 32 },
    { "tst:TRICE64 %d %d %d %d %d %d %d %d\n",                                            7466,  64, 64 },
    { "dbg:\a\a\aHi!\n",                                                                  2096,   0, 32 },
    { "rd: 0015 	%04d 	Pad with zeroes (width 4)\n",                                      3043,   4, 32 },
    { "wr:TRICE_UARTA Transmission Complete Flag is set\n",                               3283,   0, 32 },
    { "att:Executing reveived command ...\n",                                             4202,   0, 32 },
    { "sig:This ASSERT error is just a demo and no real error:\n",                        5658,   0, 32 },
    { "rd:TRICE float %9.6f (%%9.6f)\n",                                                  2220,   4, 32 },
    { "rd:TRICE32 int %d, float %f (%%f), %08x, %032b\n",                                 4362,  16, 32 },
    { "inf:TRICE_UARTB Busy Flag is set\n",                                               4290,   0, 32 },
    { "rd:TRICE32_1 line %u (%%u)\n",                                                     7679,   4, 32 },
    { "dbg:\\tHi!\n",                                                                     5722,   0, 32 },
    { "err:st64=%d < st64_1=%d\n",                                                        3183,  16, 64 },
    { "Button press at, %d\n",                                                            4863,   4, 32 },
    { "DBG:debug       message, SysTick is %6u\n",                                        5543,   4, 32 },
    { "sig:colored single letters and several TRICE macros in one line\n",                4630,   0, 32 },
    { "err:TRICE_UARTB Receiver Time Out Flag is set\n",                                  1079,   0, 32 },
    { "sig:%s\n",                                                                         7637,  -1,  8 },
    { "tst:TRICE8_11 %d %d %d %d %d %d %d %d %d %d %d\n",                                 4328,  11,  8 },
    { "tst:TRICE16_10 %d %d %d %d %d %d %d %d %d %d\n",                                   3950,  20, 16 },
    { "rd:TRICE float %+9.6f (%%9.6f)\n",                                                 6084,   0, 32 },
    { "wr:TRICE_UARTB Transmit Enable Acknowledge Flag is set\n",                         5009,   0, 32 },
    { "CYCLE:blue+i:default+h\n",                                                         5651,   0, 32 },
    { "tst:TRICE16   %%7o -> %7o %7o %7o %7o\n",                                          3281,   8, 16 },
    { "tst:TRICE8_1 %%d=%d, %%u=%u, 0x%%x=0x%x, 0x%%2x=0x%2x, 0x%%02x=0x%02x, 0x%%3x=0x%3x, 0x%%03x=0x%03x, %%b=%b\n", 5500,   8,  8 },
    { "rd: 1.234560e+02		%e 	%%e Scientific notation\n",                                  3554,   4, 32 },
    { "rd: 123.456		%g		%%g Exponent as needed, necessary digits only\n",                 2968,   8, 64 },
    { "rd: café 			%s		Plain string\n",                                                  4139,  -1,  8 },
    { "sig:TRICE64_n with 1 to 12 values\n",                                              4493,   0, 32 },
    { "dbg:12345 as 16bit is %016b\n",                                                    2906,   4, 32 },
    { "tst:TRICE32 %t %b %x %X %d %u %o %O %p %e %f %g\n",                                2108,  48, 32 },
    { "rd: 636166c3a9 		%x	Hex dump of byte values\n",                                    1033,  -1,  8 },
    { "rx:received command:%s\n",                                                         6504,  -1,  8 },
    { "s:                                          \n",                                   3685,   0, 32 },
    { "MSG: 💚 START select = %d, TriceDepthMax =%4u\n",                                5466,   4, 16 },
    { "tst:TRICE32 %d\n",                                                                 2468,   4, 32 },
    { "tst:TRICE32 %d %d %d %d %d %d %d %d %d %d %d\n",                                   1116,  44, 32 },
    { "att:...done\n",                                                                    6219,   0, 32 },
    { "wrn:Sending 254 as single byte hex: %02x\n",                                       3127,   1,  8 },
    { "sig:TRICE8_n with 1 to 12 values\n",                                               6889,   0, 32 },
    { "rd:TRICE16 %p, %p, %p, %p, %p, %p\n",                                              3413,  12, 16 },
    { "rd:TRICE16 %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                                  2626,  18, 16 },
    { "rd: 15 	%d 	Base 10\n",                                                            3430,   4, 32 },
    { "\n",                                                                               5095,   0, 32 },
    { "wrn:TRICE_UARTB CTS Flag is set\n",                                                4927,   0, 32 },
    { "MESSAGE:green+h:black\n",                                                          5589,   0, 32 },
    { "sig:TRICE16 with 1 to 12 values\n",                                                7429,   0, 32 },
    { "rd:TRICE float %-f (%%f)\n",                                                       6172,   0, 32 },
    { "tim:TRICE --------------------------------------------------\n",                   2990,   0, 32 },
    { "d:G",                                                                              7829,   0, 32 },
    { "rd: 1111 	%b 	Base 2\n",                                                           6229,   4, 32 },
    { "msg:With TRICE_S:%s\n",                                                            1436,  -1,  8 },
    { "Hello, TRICE, %d\n",                                                               4030,   4, 32 },
    { "rd:Use %%p to format a pointer in base 16 notation with leading 0x. (%p)\n",       1717,   4, 32 },
    { "dbg:Hi!\n",                                                                        6183,   0, 32 },
    { "tim:SysTick=%d\n",                                                                 7060,   4, 32 },
    { "rd:TRICE32_2 line %d,%d\n",                                                        1603,   8, 32 },
    { "rd:TRICE32_1 line %x (%%x)\n",                                                     5219,   4, 32 },
    { "tim:TRICE --------------------------------------------------\n",                   5556,   0, 32 },
    { "rd:TRICE8 line %u (%%u ,-1)\n",                                                    4893,   1,  8 },
    { "notice:TRICE8_B example:",                                                         3695,   0, 32 },
    { "att:Single Trice Stack buf size:%4u",                                              2944,   4, 32 },
    { "rd:TRICE64 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                              3696,  80, 64 },
    { "tst:TRICE32_3 %d %d %d\n",                                                         5312,  12, 32 },
    { "tst:TRICE32_7  %d %d %d %d %d %d %d\n",                                            7732,  28, 32 },
    { "rd:TRICE64 double %12.6F (%%12.6F), aDouble(y)\n",                                 2154,   8, 64 },
    { "att:mixed int & float & double & bits\n",                                          7350,   0, 32 },
    { "att:len=%u:With TRICE_B:\n",                                                       6888,   4, 32 },
    { "--------------------------------------------------\n",                             6565,   0, 32 },
    { "tst:TRICE8   %%4x -> %4x %4x %4x %4x\n",                                           1486,   4,  8 },
    { "sig:Legacy TRICE16-64\n",                                                          7394,   0, 32 },
    { "notice:TRICE32_F example:",                                                        6999,   0, 32 },
    { "att: Trice 2x half buffer size:%4u ",                                              2572,   4, 32 },
    { "rd:TRICE64 double %e (%%e), aDouble(y)\n",                                         7423,   8, 64 },
    { "rd:sizeof(%8s)",                                                                   5135,  -1,  8 },
    { "inf: Tryout buffer:",                                                              2706,   0, 32 },
    { "ATTENTION:11:green\n",                                                             3150,   0, 32 },
    { "rd:TRICE %d, %d, %d, %d, %d\n",                                                    2493,  20, 32 },
    { "rd:TRICE %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                            6090,  44, 32 },
    { "s:                                          \n",                                   2936,   0, 32 },
    { "rd:TRICE16 %p, %p, %p, %p, %p, %p, %p, %p, %p, %p, %p, %p\n",                      3313,  24, 16 },
    { "tst:TRICE32_2 %d %d\n",                                                            4577,   8, 32 },
    { "rd:TRICE %d, %d, %d, %d, %d, %d\n",                                                3618,  24, 32 },
    { "t:H",                                                                              1744,   0, 32 },
    { "rd:TRICE16_12 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                   5622,  24, 16 },
    { "rd:TRICE32 float %12.6e (%%12.6e)\n",                                              2658,   4, 32 },
    { "wrn:TRICE_UARTB Auto-Baud Rate Flag is set\n",                                     7490,   0, 32 },
    { "rd:TRICE %d, %d, %d, %d, %d, %d, %d\n",                                            7990,  28, 32 },
    { "rd:TRICE8 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                           6823,  11,  8 },
    { "rd:TRICE32_5 %d, %d, %d, %d, %d\n",                                                6340,  20, 32 },
    { "tst:TRICE64 %d %d %d %d %d %d %d\n",                                               7713,  56, 64 },
    { "att:Single Trice Stack buf size:%4u",                                              2958,   4, 32 },
    { "rd:TRICE32_7 %d, %d, %d, %d, %d, %d, %d\n",                                        3362,  28, 32 },
    { "tst:TRICE8_9  %d %d %d %d %d %d %d %d %d\n",                                       5405,   9,  8 },
    { "tst:TRICE64_6  %d %d %d %d %d %d\n",                                               3996,  48, 64 },
    { "rd:TRICE float %+.9f (%%.9f)\n",                                                   4633,   0, 32 },
    { "wr:TRICE_UARTA Transmit Enable Acknowledge Flag is set\n",                         6208,   0, 32 },
    { "err:TRICE_UARTA Parity Error Flag is set\n",                                       5529,   0, 32 },
    { "tim:TRICE START time message\n",                                                   4965,   0, 32 },
    { "rd:TRICE16_1 %d\n",                                                                2697,   2, 16 },
    { "rd:TRICE16 %X, %X, %X, %X, %X, %X, %X, %X, %X, %X, %X, %X\n",                      2700,  24, 16 },
    { "tst:TRICE8_1  %d\n",                                                               1287,   1,  8 },
    { "tst:TRICE32 %d %d %d %d %d %d\n",                                                  6903,  24, 32 },
    { "tst:TRICE64_1  %d\n",                                                              1177,   8, 64 },
    { "rd:TRICE %d\n",                                                                    4346,   4, 32 },
    { "MSG:normal      message, SysTick is %6u\n",                                        3047,   4, 32 },
    { "rd:TRICE64 double %12.6G (%%12.6G), aDouble(y)\n",                                 4949,   8, 64 },
    { "tst:TRICE16 %t %b %x %X %d %u %o %O %p\n",                                         1374,  18, 16 },
    { "rd:TRICE32_1 float %e (%%e)\n",                                                    1311,   4, 32 },
    { "sig:Runtime generated strings\n",                                                  3056,   0, 32 },
    { "rd:TRICE_UARTB Receive Enable Acknowledge Flag is set\n",                          7209,   0, 32 },
    { "s:                                          \n",                                   5096,   0, 32 },
    { "tim:SysTick=%d\n",                                                                 3742,   4, 32 },
    { "ERROR:11:red\n",                                                                   7846,   0, 32 },
    { "rd:TRICE16 %p, %p\n",                                                              5677,   4, 16 },
    { "INFO:informal   message, SysTick is %6u\n",                                        2459,   4, 32 },
    { "rd:TRICE float %-9.6f (%%9.6f)\n",                                                 7112,   0, 32 },
    { "rd:TRICE64_1 double %F (%%F), aDouble(y)\n",                                       6033,   8, 64 },
    { "rd:TRICE8 line %x (%%x ,-1)\n",                                                    7752,   1,  8 },
    { "rd:TRICE16_1 line %d (%%d -1)\n",                                                  5288,   2, 16 },
    { "rd:sizeof(%8s)",                                                                   5152,  -1,  8 },
    { "err:TRICE_UARTA Noise error detected Flag is set\n",                               4888,   0, 32 },
    { "wrn:Transmit buffer truncated from %u to %u\n",                                    2240,   8, 32 },
    { "rd:TRICE16 %p, %p, %p, %p, %p\n",                                                  7576,  10, 16 },
    { "tst:TRICE32_2 %u %u\n",                                                            5082,   8, 32 },
    { "rd:TRICE8 line %t (%%t ,0)\n",                                                     1857,   1,  8 },
    { "RECEIVE:black+h:black\n",                                                          6334,   0, 32 },
    { "tst:TRICE8_4 %u %u %u %u\n",                                                       3027,   4,  8 },
    { "tst:TRICE32_1  %d\n",                                                              7894,   4, 32 },
    { "rd:TRICE line %x (%%x)\n",                                                         7458,   4, 32 },
    { "wrn:TRICE_UARTB Send Break Flag is set\n",                                         3302,   0, 32 },
    { "sig:Runtime generated strings\n",                                                  4995,   0, 32 },
    { "tst:TRICE8 %d %d %d %d %d %d %d %d %d %d %d\n",                                    1424,  11,  8 },
    { "s:                                          \n",                                   3548,   0, 32 },
    { "sig:TRICE16 with 1 to 12 pointer\n",                                               3923,   0, 32 },
    { "tst:TRICE64_2 %x %x\n",                                                            4882,  16, 64 },
    { "ISR:interrupt   message, SysTick is %6u\n",                                        5773,   4, 32 },
    { "tst:TRICE8_3 %d %d %d\n",                                                          3021,   3,  8 },
    { "tst:TRICE8 %d %d %d %d %d %d %d %d %d %d %d %d\n",                                 6831,  12,  8 },
    { "tst:TRICE32_12 %d %d %d %d %d %d %d %d %d %d %d %d\n",                             7143,  48, 32 },
    { "sig:TRICE8 with 1 to 12 values\n",                                                 2228,   0, 32 },
    { "tst:TRICE32 %d %d\n",                                                              3673,   8, 32 },
    { "rd:TRICE64_1 double %g (%%g), aDouble(y)\n",                                       3522,   8, 64 },
    { "tst:TRICE32 %d %d %d %d %d %d %d\n",                                               5657,  28, 32 },
    { "att:Various single arguments\n",                                                   6124,   0, 32 },
    { "s:     \n",                                                                        1631,   0, 32 },
    { "dbg:\aHi!\n",                                                                      7147,   0, 32 },
    { "rd:TRICE16 %X, %X\n",                                                              2216,   4, 16 },
    { "rd:TRICE16_1 line %b (%%b -1)\n",                                                  4509,   2, 16 },
    { "msg:x = %g = %d.%03d, %d.%03d\n",                                                  4716,  20, 32 },
    { "rd:TRICE32_1 line %b (%%b)\n",                                                     5550,   4, 32 },
    { "rd:TRICE32 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                              6218,  40, 32 },
    { "dbg:len=%u: ",                                                                     3619,   4, 32 },
    { "rd:TRICE line %b (%%b)\n",                                                         4896,   4, 32 },
    { "att: Trice 2x half buffer size:%4u ",                                              4519,   4, 32 },
    { "err:TRICE_UARTB Auto-Baud Rate Error Flag is set\n",                               4325,   0, 32 },
    { "allert:magenta:magenta+h\n",                                                       3309,   0, 32 },
    { "rd:TRICE64 %d, %d\n",                                                              5866,  16, 64 },
    { "time: %d µs - ReadUs32() lasts %d ticks\n",                                       5422,   8, 32 },
    { "rd:TRICE float %-.9f (%%.9f)\n",                                                   3925,   0, 32 },
    { "tim:TRICE --------------------------------------------------\n",                   6258,   0, 32 },
    { "rd:TRICE32 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                          6864,  44, 32 },
    { "att:TRICE64 %70b\n",                                                               1221,   8, 64 },
    { "tst:TRICE8_3 %u %u %u\n",                                                          4167,   3,  8 },
    { "4",                                                                                3837,   0, 32 },
    { "rd:TRICE float %9f (%%9f)\n",                                                      3606,   4, 32 },
    { "rd:TRICE64 %d, %d, %d, %d\n",                                                      7047,  32, 64 },
    { "att:TRICE32 %40b\n",                                                               4886,   4, 32 },
    { "tst:TRICE8 %d %d %d %d %d %d %d %d\n",                                             1363,   8,  8 },
    { "warning:11+i:red\n",                                                               1052,   0, 32 },
    { "\n",                                                                               4774,   0, 32 },
    { "rd:TRICE16 %X, %X, %X, %X, %X, %X\n",                                              2313,  12, 16 },
    { "rd: 1.234560e+02		%e 	%%e Scientific notation\n",                                  7792,   8, 64 },
    { "err:TRICE_UARTA Auto-Baud Rate Error Flag is set\n",                               3872,   0, 32 },
    { "tst:TRICE32_8  %d %d %d %d %d %d %d %d\n",                                         4772,  32, 32 },
    { "tst:TRICE8 %t %b %x %X %d %u %o %O %p\n",                                          6042,   9,  8 },
    { "\n",                                                                               3130,   0, 32 },
    { "rd:TRICE8 %d, %d\n",                                                               6821,   2,  8 },
    { "rd:TRICE16 %X, %X, %X, %X\n",                                                      2529,   8, 16 },
    { "tst:TRICE8_4 %02x %02x %02x %02x\n",                                               3418,   4,  8 },
    { "rd:TRICE32_1 float %E (%%E)\n",                                                    4686,   4, 32 },
    { "sig:TRICE16 with variable param count 1 to 12\n",                                  6236,   0, 32 },
    { "rd:TRICE16 %d, %d, %d, %d, %d, %d\n",                                              6750,  12, 16 },
    { "rd:TRICE32_8 %d, %d, %d, %d, %d, %d, %d, %d\n",                                    7378,  32, 32 },
    { "rd:TRICE64_1 %d\n",                                                                2845,   8, 64 },
    { "tst:TRICE8_8 %u %u %u %u %u %u %u %u\n",                                           5745,   8,  8 },
    { "tst:TRICE64_1 %x\n",                                                               3903,   8, 64 },
    { "rd:e\n",                                                                           7275,   0, 32 },
    { "DEBUG:130+i\n",                                                                    3111,   0, 32 },
    { "trace:default+i:default+h\n",                                                      6639,   0, 32 },
    { "SIG:signal      message, SysTick is %6u\n",                                        4586,   4, 32 },
    { "tst:TRICE8_1 %u\n",                                                                7491,   1,  8 },
    { " = %d\n",                                                                          6144,   4, 32 },
    { "rd:TRICE16_3 %d, %d, %d\n",                                                        5086,   6, 16 },
    { "signal:TRICE32_n with 1 to 12 values\n",                                           2394,   0, 32 },
    { "tst:TRICE8_7 %u %u %u %u %u %u %u\n",                                              7037,   7,  8 },
    { "sig:Runtime generated strings\n",                                                  5420,   0, 32 },
    { "rd:TRICE float %E (%%E)\n",                                                        1770,   4, 32 },
    { "err:TRICE_UARTB OverRun Error Flag is set\n",                                      1773,   0, 32 },
    { "rd:TRICE32_9 %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                                3526,  36, 32 },
    { "rd: ␣␣123.46		%8.2f	%%8.2f Width 8, precision 2\n",                            3790,   4, 32 },
    { "tim: post TriceEncryption SysTick=%d\n",                                           6901,   4, 32 },
    { "CRITICAL:red+i:default+h\n",                                                       2244,   0, 32 },
    { "read:black+i:yellow+h\n",                                                          4573,   0, 32 },
    { "write:black+u:yellow+h\n",                                                         1606,   0, 32 },
    { "tim:TRICE --------------------------------------------------\n",                   6283,   0, 32 },
    { "rd:TRICE16 %d, %d\n",                                                              6706,   4, 16 },
    { "w:B",                                                                              5090,   0, 32 },
    { "rd:TRICE16 %p\n",                                                                  2676,   2, 16 },
    { "rd:TRICE32 %d\n",                                                                  5489,   4, 32 },
    { "diag:f",                                                                           1264,   0, 32 },
    { "tst:TRICE8 %d\n",                                                                  4024,   1,  8 },
    { "tst:TRICE64 %d %d %d %d %d %d %d %d %d\n",                                         2004,  72, 64 },
    { "tst:TRICE8  %%08b -> %08b %08b %08b %08b\n",                                       4601,   4,  8 },
    { "rd: U+0041 'A' 	%#U 	Unicode with character\n",                                    1964,   0, 32 },
    { "rd:Use %%p to format a pointer in base 16 notation with leading 0x. (%p)\n",       1507,   8, 64 },
    { "rd:TRICE float %+f (%%f)\n",                                                       3701,   0, 32 },
    { "rd:TRICE64 int %d, double %f (%%f), %016x, %064b\n",                               5593,  32, 64 },
    { "wrn:TRICE_UARTB IDLE line detected Flag is set\n",                                 4465,   0, 32 },
    { "wr:TRICE_UARTA Transmit Enable Acknowledge Flag is set\n",                         2024,   0, 32 },
    { "notice:TRICE32_B example:",                                                        5766,   0, 32 },
    { "tst:TRICE8   %%4u -> %4u %4u %4u %4u\n",                                           4454,   4,  8 },
    { "tst:TRICE16  %%05x ->   %05x   %05x   %05x   %05x\n",                              5900,   8, 16 },
    { "tst:TRICE8_7 %d %d %d %d %d %d %d\n",                                              2524,   7,  8 },
    { "rd: 0xf 	%#x 	Base 16, with leading 0x\n",                                         1873,   4, 32 },
    { "tst:TRICE8_3  %d %d %d\n",                                                         3422,   3,  8 },
    { "rd:TRICE float %-9f (%%9f)\n",                                                     5851,   0, 32 },
    { "assert:yellow+i:blue\n",                                                           3897,   0, 32 },
    { "tst:TRICE8_6 %02x %02x %02x %02x %02x %02x\n",                                     7880,   6,  8 },
    { "wrn:TRICE_UARTB Receive Wake Up from mute mode Flag is set\n",                     3652,   0, 32 },
    { "Hello, TRICE\n",                                                                   4683,   0, 32 },
    { "tim:TRICE --------------------------------------------------\n",                   7735,   0, 32 },
    { "sig:%s\n",                                                                         5176,  -1,  8 },
    { "rd: U+0041 	%U 	Unicode\n",                                                        6044,   0, 32 },
    { "s:     ",                                                                          3723,   0, 32 },
    { "rd:TRICE %d, %d\n",                                                                5585,   8, 32 },
    { "tst:TRICE8_6 %d %d %d %d %d %d\n",                                                 1792,   6,  8 },
    { "rd:Use %%p to format a pointer in base 16 notation with leading 0x. (%p)\n",       7074,   1,  8 },
    { "rd:TRICE float %e (%%e)\n",                                                        7902,   4, 32 },
    { "time: %d µs - ReadUs32() lasts %d ticks\n",                                       1962,   8, 32 },
    { "rd:TRICE %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                        5495,  48, 32 },
    { "rd:TRICE16 %X, %X, %X, %X, %X, %X, %X\n",                                          2265,  14, 16 },
    { "m:12",                                                                             3029,   0, 32 },
    { "sig:Boolean (true/false)\n",                                                       2567,   0, 32 },
    { "rd:Use %%t to format a boolean as true (%t) or false (%t).\n",                     7736,   8, 32 },
    { "TIM:timing      message, SysTick is %6u\n",                                        1316,   4, 32 },
    { "wr:d",                                                                             1790,   0, 32 },
    { "tst:TRICE16 %d %d %d %d %d %d %d %d\n",                                            5896,  16, 16 },
    { "rd:TRICE float %F (%%F)\n",                                                        1151,   4, 32 },
    { "rd:TRICE32 float %12.6G (%%12.6G)\n",                                              4932,   4, 32 },
    { "err:TRICE_UARTA Noise error detected Flag is set\n",                               3102,   0, 32 },
    { "FATAL:magenta+b:red\n",                                                            7420,   0, 32 },
    { "tst:TRICE16_2 %u %u\n",                                                            4308,   4, 16 },
    { "tst:TRICE16 %d %d %d %d %d %d %d %d %d %d %d\n",                                   2157,  22, 16 },
    { "err:TRICE_UARTB Noise error detected Flag is set\n",                               5496,   0, 32 },
    { "s:                                          \n",                                   1493,   0, 32 },
    { "rd:TRICE16 %X, %X, %X, %X, %X, %X, %X, %X, %X, %X\n",                              6108,  20, 16 },
    { "err:TRICE_UARTB Parity Error Flag is set\n",                                       6905,   0, 32 },
    { "rd: 15   	%-4d 	Pad with spaces (width 4, left justified)\n",                      3775,   0, 32 },
    { "tst:TRICE16_5  %d %d %d %d %d\n",                                                  1035,  10, 16 },
    { "rd:TRICE float %-.9f (%%.9f)\n",                                                   1586,   0, 32 },
    { "rd:TRICE16 %p, %p, %p\n",                                                          1218,   6, 16 },
    { "rd:TRICE32 %d, %d, %d, %d, %d, %d, %d, %d\n",                                      6510,  32, 32 },
    { "tst:TRICE16_8  %d %d %d %d %d %d %d %d\n",                                         7621,  16, 16 },
    { "tim: pre TriceEncryption SysTick=%d\n",                                            6649,   4, 32 },
    { "tim:TRICE --------------------------------------------------\n",                   5966,   0, 32 },
    { "tst:TRICE64_8  %d %d %d %d %d %d %d %d\n",                                         4247,  64, 64 },
    { "rd:TRICE float %g (%%g)\n",                                                        4536,   4, 32 },
    { "s:     ",                                                                          7563,   0, 32 },
    { "dbg:\\aHi!\n",                                                                     6987,   0, 32 },
    { "rd:TRICE float %G (%%G)\n",                                                        7325,   4, 32 },
    { "notice:TRICE_F example: ",                                                         6381,   0, 32 },
    { "s:     \n",                                                                        3625,   0, 32 },
    { "rd:TRICE64_1 line %d (%%d)\n",                                                     7508,   8, 64 },
    { "rd:TRICE %d, %d, %d, %d, %d, %d, %d, %d\n",                                        3339,  32, 32 },
    { "sig:Pointer (hex)\n",                                                              7599,   0, 32 },
    { "rd: 123.456		%g		%%g Exponent as needed, necessary digits only\n",                 3340,   4, 32 },
    { "rd: café␣␣ 		%-6s 		Width 6, left justify\n",                                 7906,  -1,  8 },
    { "rd:TRICE64 double %12.6g (%%12.6g), aDouble(y)\n",                                 6598,   8, 64 },
    { "rd:TRICE64_5 %d, %d, %d, %d, %d\n",                                                7969,  40, 64 },
    { "tst:TRICE8_3 %02x %02x %02x\n",                                                    4623,   3,  8 },
    { "WARNING:USART1 OverRun Error Flag is set!\n",                                      1583,   0, 32 },
    { "wrn:TRICE_UARTB Character Match Flag is set\n",                                    4181,   0, 32 },
    { "rx:received command:%s\n",                                                         5218,  -1,  8 },
    { "rd:TRICE64 line %F (%%F)\n",                                                       5474,   8, 64 },
    { "rd:Use %%p to format a pointer in base 16 notation with leading 0x. (%p)\n",       1536,   4, 32 },
    { "tst:TRICE64 %t %b %x %X %d %u %o %O %p %e %f %g\n",                                3301,  96, 64 },
    { "wrn:TRICE_UARTA CTS interrupt Flag is set\n",                                      2797,   0, 32 },
    { "2",                                                                                5605,   0, 32 },
    { "tst:TRICE64 %d %d %d %d %d %d\n",                                                  6175,  48, 64 },
    { "rd:TRICE8 %d, %d, %d, %d\n",                                                       2955,   4,  8 },
    { "rd:TRICE16_1 line %t (%%t ,2)\n",                                                  5802,   2, 16 },
    { "wrn:TRICE_UARTB CTS interrupt Flag is set\n",                                      1037,   0, 32 },
    { "rd:TRICE32_11 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                       4194,  44, 32 },
    { "tst:TRICE8_2 %d %d\n",                                                             2787,   2,  8 },
    { "tst:TRICE64_11 %d %d %d %d %d %d %d %d %d %d %d\n",                                7443,  88, 64 },
    { "rd:TRICE64_1 line %O (%%O)\n",                                                     7612,   8, 64 },
    { "tst:TRICE32_1 %d\n",                                                               1727,   4, 32 },
    { "sig:%s\n",                                                                         1235,  -1,  8 },
    { "rd:TRICE32 int %d, float %f (%%f), %08x, %032b\n",                                 7353,  16, 32 },
    { "rd:TRICE8 line %O (%%O ,-1)\n",                                                    7189,   1,  8 },
    { "message:green+h:black\n",                                                          5572,   0, 32 },
    { "rd:TRICE64_1 line %X (%%C)\n",                                                     4929,   8, 64 },
    { "rd:TRICE64 %d, %d\n",                                                              7624,  16, 64 },
    { "rd:TRICE64 double %G (%%G), aDouble(y)\n",                                         5738,   8, 64 },
    { "rd:TRICE line %t (%%t -1)\n",                                                      1057,   4, 32 },
    { "tst:TRICE16_4 %d %d %d %d\n",                                                      4728,   8, 16 },
    { "tst:TRICE32_6  %d %d %d %d %d %d\n",                                               5830,  24, 32 },
    { "rd:TRICE64 double %g (%%g), aDouble(y)\n",                                         2683,   8, 64 },
    { "tst:TRICE8 %d %d %d %d %d\n",                                                      7053,   5,  8 },
    { "tst:TRICE32_5  %d %d %d %d %d\n",                                                  4587,  20, 32 },
    { "rd:TRICE64 %d, %d, %d, %d, %d, %d, %d, %d\n",                                      1761,  64, 64 },
    { "rd:TRICE64_3 %d, %d, %d\n",                                                        6955,  24, 64 },
    { "s:     ",                                                                          1595,   0, 32 },
    { "rd:TRICE64_7 %d, %d, %d, %d, %d, %d, %d\n",                                        6851,  56, 64 },
    { "rd:TRICE float %+f (%%f)\n",                                                       7886,   0, 32 },
    { "critical:red+i:default+h\n",                                                       6227,   0, 32 },
    { "tim:TRICE --------------------------------------------------\n",                   5553,   0, 32 },
    { "rd:TRICE8_2 %d, %d\n",                                                             1120,   2,  8 },
    { "tst:TRICE16_3 %d %d %d\n",                                                         7510,   6, 16 },
    { "tst:TRICE64 %d %d %d %d %d %d %d %d %d %d %d %d\n",                                7598,  96, 64 },
    { "NOTICE:blue:white+h\n",                                                            4609,   0, 32 },
    { "rd:TRICE64_1 line %b (%%b)\n",                                                     6341,   8, 64 },
    { "rd:TRICE32 %d, %d\n",                                                              5560,   8, 32 },
    { "rd:TRICE32 float %12.6F (%%12.6F)\n",                                              1164,   4, 32 },
    { "inf: Tryout rx struct:",                                                           7187,   0, 32 },
    { "err:TRICE_UARTB Auto-Baud Rate Error Flag is set\n",                               4553,   0, 32 },
    { "rd:TRICE16 %X, %X, %X, %X, %X\n",                                                  7966,  10, 16 },
    { "e:A",                                                                              1375,   0, 32 },
    { "rd:TRICE16 %p, %p, %p, %p, %p, %p, %p, %p, %p\n",                                  5870,  18, 16 },
    { "rd:TRICE64 %d, %d, %d\n",                                                          1632,  24, 64 },
    { "err:TRICE_UARTA Auto-Baud Rate Error Flag is set\n",                               2766,   0, 32 },
    { "rd:TRICE line %G (%%G)\n",                                                         5712,   4, 32 },
    { "tst:TRICE8   %%4X -> %4X %4X %4X %4X\n",                                           4288,   4,  8 },
    { "tst:TRICE8_2 %02x %02x\n",                                                         2805,   2,  8 },
    { "tst:TRICE64_4  %d %d %d %d\n",                                                     5684,  32, 64 },
    { "rd:TRICE16_1 line %t (%%t ,0)\n",                                                  1220,   2, 16 },
    { "s:                                          \n",                                   1089,   0, 32 },
    { "default:off\n",                                                                    4554,   0, 32 },
    { "att: TriceEncrypted =  %08x %08x %08x %08x %08x %08x\n",                           7140,  24, 32 },
    { "wrn:TRICE_UARTB CTS Flag is set\n",                                                4349,   0, 32 },
    { "s:     \n",                                                                        1530,   0, 32 },
    { "INTERRUPT:magenta+i:default+h\n",                                                  6078,   0, 32 },
    { "tst:TRICE64_1 %d\n",                                                               1165,   8, 64 },
    { "tst:TRICE8_7  %d %d %d %d %d %d %d\n",                                             1293,   7,  8 },
    { "rd:TRICE line %d (%%d)\n",                                                         3963,   4, 32 },
    { "rd:TRICE32_1 line %d (%%d)\n",                                                     5595,   4, 32 },
    { "WRITE:black+u:yellow+h\n",                                                         7707,   0, 32 },
    { "TEST:yellow+h:black\n",                                                            1931,   0, 32 },
    { "rd:TRICE %d, %d, %d\n",                                                            5114,  12, 32 },
    { "rd:TRICE %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                                6850,  40, 32 },
    { "tst:TRICE16 %d %d %d\n",                                                           7710,   6, 16 },
    { " = %d\n",                                                                          3355,   4, 32 },
    { "rd:TRICE16 %d, %d, %d, %d, %d\n",                                                  6266,  10, 16 },
    { "rd:TRICE16_5 %d, %d, %d, %d, %d\n",                                                4651,  10, 16 },
    { "rd:TRICE64_8 %d, %d, %d, %d, %d, %d, %d, %d\n",                                    5725,  64, 64 },
    { "dbg:k\n",                                                                          6014,   0, 32 },
    { "rd:e\n",                                                                           7539,   0, 32 },
    { "rd: 'A' 	%q 	Quoted character\n",                                                  2970,   4, 32 },
    { "tim:TRICE STOP time message\n",                                                    7388,   0, 32 },
    { "rx:received command:%s\n",                                                         1202,  -1,  8 },
    { "Hello, TRICE\n",                                                                   2926,   0, 32 },
    { "att:Executing command %s ...\n",                                                   5044,  -1,  8 },
    { "s:                                          \n",                                   5910,   0, 32 },
    { "\natt:Software Transmit UART Component demo\n",                                    7447,   0, 32 },
    { "tim:TRICE --------------------------------------------------\n",                   2869,   0, 32 },
    { "tst:TRICE8   %%8b -> %8b %8b %8b %8b\n",                                           3425,   4,  8 },
    { "rd:TRICE float %.9f (%%.9f)\n",                                                    4295,   4, 32 },
    { "rd:TRICE32_1 float %F (%%F)\n",                                                    7390,   4, 32 },
    { "rd:TRICE16 %d, %d, %d, %d, %d, %d, %d\n",                                          6634,  14, 16 },
    { "tst:TRICE8_6 %u %u %u %u %u %u\n",                                                 1602,   6,  8 },
    { "rd:TRICE float %G (%%G)\n",                                                        1890,   4, 32 },
    { "\n",                                                                               6623,   0, 32 },
    { "rd:TRICE8_4 %d, %d, %d, %d\n",                                                     3465,   4,  8 },
    { "rd:TRICE64 int %d, double %f (%%f), %016x, %064b\n",                               5698,  32, 64 },
    { "ASSERT:yellow+i:blue\n",                                                           5292,   0, 32 },
    { "rd:TRICE64 line %E (%%E)\n",                                                       7618,   8, 64 },
    { "rd:TRICE64_9 %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                                5735,  72, 64 },
    { "s:                                          \n",                                   3748,   0, 32 },
    { "tst:TRICE64 %d %d %d %d\n",                                                        7692,  32, 64 },
    { "att:negative float & double\n",                                                    6569,   0, 32 },
    { "wrn:TRICE_UARTB CTS interrupt Flag is set\n",                                      7641,   0, 32 },
    { "inf:rx:USART2 rx:",                                                                1219,   0, 32 },
    { "tst:TRICE8   %%4O -> %4O %4O %4O %4O\n",                                           7208,   4,  8 },
    { "rd:TRICE float %e (%%e)\n",                                                        3801,   4, 32 },
    { "wrn:TRICE_UARTB IDLE line detected Flag is set\n",                                 3198,   0, 32 },
    { "rd: 63 61 66 c3 a9 	% x	Hex dump with spaces\n",                                   4405,  -1,  8 },
    { "tst:TRICE64 %d %d %d\n",                                                           7907,  24, 64 },
    { "MSG: ✅ STOP  select = %d, TriceDepthMax =%4u\n",                                 4416,   4, 16 },
    { "rd:TRICE32 int %d, float %f (%%f), %08x, %032b\n",                                 1841,  16, 32 },
    { "cycle:blue+i:default+h\n",                                                         4798,   0, 32 },
    { "tst:TRICE8_5 %d %d %d %d %d\n",                                                    2498,   5,  8 },
    { "tst:TRICE16_4 %u %u %u %u\n",                                                      1786,   8, 16 },
    { "tst:TRICE16 %t %b %x %X %d %u %o %O %p\n",                                         3417,  18, 16 },
    { "rd:TRICE float %g (%%g)\n",                                                        4186,   4, 32 },
    { "rd:TRICE64 double %f (%%f), aDouble(y)\n",                                         3911,   8, 64 },
    { "tst:TRICE32_9  %d %d %d %d %d %d %d %d %d\n",                                      7577,  36, 32 },
    { "rd:TRICE32_1 float %g (%%g)\n",                                                    5212,   4, 32 },
    { "rd:TRICE64 double %g (%%g), aDouble(y)\n",                                         4535,   8, 64 },
    { "s:                                          \n",                                   2209,   0, 32 },
    { "tim:TRICE --------------------------------------------------\n",                   5976,   0, 32 },
    { "tst:TRICE32_4 %x %x %x %x\n",                                                      6859,  16, 32 },
    { "sig:Runtime generated strings\n",                                                  1014,   0, 32 },
    { "tst:TRICE8 %d %d %d %d %d %d %d %d %d\n",                                          5413,   9,  8 },
    { "emergency:red+i:blue\n",                                                           6257,   0, 32 },
    { "test:yellow+h:black\n",                                                            4171,   0, 32 },
    { "rd:TRICE16_9 %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                                4396,  18, 16 },
    { "rd:TRICE8 line %d (%%d ,-1)\n",                                                    1294,   1,  8 },
    { "rd:TRICE64_1 %d\n",                                                                4144,   8, 64 },
    { "rd:TRICE8_5 %d, %d, %d, %d, %d\n",                                                 5134,   5,  8 },
    { "rd:TRICE32_1 line %o (%%o)\n",                                                     7867,   4, 32 },
    { "rd: 123.456000		%f 	%%f Decimal point, no exponent\n",                             2554,   4, 32 },
    { "rd:TRICE8 line %X (%%X ,-1)\n",                                                    6875,   1,  8 },
    { "\n",                                                                               6717,   0, 32 },
    { "rd:TRICE32_10 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                           5859,  40, 32 },
    { "rd:   15 	%4d 	Pad with spaces (width 4, right justified)\n",                      5696,   4, 32 },
    { "tst:TRICE8_6  %d %d %d %d %d %d\n",                                                4221,   6,  8 },
    { "tim: post TriceDecryption SysTick=%d\n",                                           6241,   2, 16 },
    { "inf:TRICE_UARTB Busy Flag is set\n",                                               6349,   0, 32 },
    { "s:                                          \n",                                   5493,   0, 32 },
    { "TRANSMIT:black:black+h\n",                                                         1556,   0, 32 },
    { "rd:TRICE64 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                      1306,  96, 64 },
    { "sig:%s\n",                                                                         4470,  -1,  8 },
    { "tst:TRICE16_12 %d %d %d %d %d %d %d %d %d %d %d %d\n",                             1814,  24, 16 },
    { "rd:TRICE float %f (%%f)\n",                                                        4605,   4, 32 },
    { "inf:TRICE_UARTA Busy Flag is set\n",                                               7474,   0, 32 },
    { "wrn:TRICE_UARTB Character Match Flag is set\n",                                    1932,   0, 32 },
    { "wrn:TRICE_UARTA Auto-Baud Rate Flag is set\n",                                     4611,   0, 32 },
    { "dbg:\t\tHi!\n",                                                                    6245,   0, 32 },
    { "--------------------------------------------------\n",                             2121,   0, 32 },
    { "rd:TRICE64 double %12.6E (%%12.6E), aDouble(y)\n",                                 3097,   8, 64 },
    { "sig:%s\n",                                                                         5928,  -1,  8 },
    { "tst:TRICE8_8 %d %d %d %d %d %d %d %d\n",                                           1030,   8,  8 },
    { "tst:TRICE32_2  %d %d\n",                                                           5612,   8, 32 },
    { "tst:TRICE64_5  %d %d %d %d %d\n",                                                  6946,  40, 64 },
    { "rd:TRICE64_2 line %d,%d\n",                                                        7163,  16, 64 },
    { "rd:TRICE %d, %d, %d, %d\n",                                                        6099,  16, 32 },
    { "rd:TRICE16_4 %d, %d, %d, %d\n",                                                    7226,   8, 16 },
    { "rd:TRICE64 %d\n",                                                                  7873,   8, 64 },
    { "msg: message = %08x %08x %08x %08x %08x %08x\n",                                   7881,  24, 32 },
    { "sig:TRICE16 with 1 to 12 hex\n",                                                   3303,   0, 32 },
    { "rd:TRICE float %E (%%E)\n",                                                        1784,   4, 32 },
    { "err:TRICE_UARTB OverRun Error Flag is set\n",                                      6115,   0, 32 },
    { "rd:TRICE float %+9f (%%9f)\n",                                                     2996,   0, 32 },
    { "rd:TRICE64_1 double %E (%%E), aDouble(y)\n",                                       5373,   8, 64 },
    { "rd:TRICE16 %X, %X, %X, %X, %X, %X, %X, %X\n",                                      7807,  16, 16 },
    { "att:formatted float & double\n",                                                   4366,   0, 32 },
    { "wrn:TRICE_UARTB Auto-Baud Rate Flag is set\n",                                     7144,   0, 32 },
    { "err:TRICE_UARTA Framing Error Flag is set\n",                                      1620,   0, 32 },
    { "rd:TRICE_UARTA Receive Enable Acknowledge Flag is set\n",                          6192,   0, 32 },
    { "transmit:black:black+h\n",                                                         5762,   0, 32 },
    { "time:TRICE32_1  message, SysTick is %6u\n",                                        4444,   4, 32 },
    { "tst:TRICE8_1 %d\n",                                                                2803,   1,  8 },
    { "tst:TRICE16 %d %d\n",                                                              5739,   4, 16 },
    { "tst:TRICE16 %d %d %d %d %d %d %d %d %d\n",                                         6585,  18, 16 },
    { "wrn:TRICE_UARTA Send Break Flag is set\n",                                         5063,   0, 32 },
    { "rd:TRICE16 %X, %X, %X\n",                                                          3850,   6, 16 },
    { "tst:TRICE32_11 %d %d %d %d %d %d %d %d %d %d %d\n",                                4996,  44, 32 },
    { "notice:TRICE16_F example:",                                                        4491,   0, 32 },
    { "Hello, TRICE0()\n",                                                                7263,   0, 32 },
    { "tst:TRICE8_5 %d %d %d %d %d\n",                                                    1509,   5,  8 },
    { "tst:TRICE8_8 %d %d %d %d %d %d %d %d\n",                                           3933,   8,  8 },
    { "tst:TRICE64_12 %t %b %x %X %d %u %o %O %p %e %f %g\n",                             2967,  96, 64 },
    { "rd:TRICE64_1 double %f (%%f), aDouble(y)\n",                                       3502,   8, 64 },
    { "rd:TRICE64 double %F (%%F), aDouble(y)\n",                                         1907,   8, 64 },
    { "\n",                                                                               7051,   0, 32 },
    { "DIAG:yellow+i:default+h\n",                                                        6822,   0, 32 },
    { "tst:TRICE64_10 %d %d %d %d %d %d %d %d %d %d\n",                                   6036,  80, 64 },
    { "rd:TRICE32_1 float %f (%%f)\n",                                                    2784,   4, 32 },
    { "attention:11:green\n",                                                             2635,   0, 32 },
    { "rd:TRICE32_1 line %O (%%O)\n",                                                     7875,   4, 32 },
    { "rd:TRICE16_8 %d, %d, %d, %d, %d, %d, %d, %d\n",                                    4458,  16, 16 },
    { "rd:TRICE16_10 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                           3901,  20, 16 },
    { "rd:TRICE32_4 %d, %d, %d, %d\n",                                                    3782,  16, 32 },
    { "tst:TRICE8_8  %d %d %d %d %d %d %d %d\n",                                          7949,   8,  8 },
    { "MSG:triceFifoDepthMax = %d of max %d, triceStreamBufferDepthMax = %d of max %d\n", 4833,  16, 32 },
    { "rd:TRICE8 %d, %d, %d, %d, %d, %d, %d, %d\n",                                       3598,   8,  8 },
    { "sig:Integer (indent, base, sign)\n",                                               2639,   0, 32 },
    { "tim:TRICE START time message\n",                                                   4826,   0, 32 },
    { "rd:TRICE64_1 double %G (%%G), aDouble(y)\n",                                       3952,   8, 64 },
    { "rd:TRICE64_1 double %e (%%e), aDouble(y)\n",                                       2246,   8, 64 },
    { "\n",                                                                               2454,   0, 32 },
    { "rd:TRICE8_7 %d, %d, %d, %d, %d, %d, %d\n",                                         3444,   7,  8 },
    { "WARNING:USART1 OverRun Error Flag is set!\n",                                      4272,   0, 32 },
    { "err:TRICE_UARTA Parity Error Flag is set\n",                                       1941,   0, 32 },
    { "err:TRICE_UARTA OverRun Error Flag is set\n",                                      4872,   0, 32 },
    { "rd:TRICE8_11 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                        3273,  11,  8 },
    { "tst:TRICE16_1 %d\n",                                                               2902,   2, 16 },
    { "MSG: 💚 START select = %d\n",                                                    7809,   2, 16 },
    { "rd:TRICE8 %d, %d, %d\n",                                                           2030,   3,  8 },
    { "tst:TRICE8_4 %d %d %d %d\n",                                                       3319,   4,  8 },
    { "tst:TRICE64_9  %d %d %d %d %d %d %d %d %d\n",                                      6178,  72, 64 },
    { "rd:TRICE64 double %12.6e (%%12.6e), aDouble(y)\n",                                 6113,   8, 64 },
    { "rd:TRICE64 int %d, double %f (%%f), %016x, %064b\n",                               3306,  32, 64 },
    { "rd:TRICE16 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                              7537,  20, 16 },
    { "rd: F 	%X 	Base 16, uppercase\n",                                                  1470,   4, 32 },
    { "tst:TRICE16_2  %d %d\n",                                                           4296,   4, 16 },
    { "tst:TRICE32 %d %d %d %d %d %d %d %d %d\n",                                         4378,  36, 32 },
    { "tst:TRICE64_7  %d %d %d %d %d %d %d\n",                                            3656,  56, 64 },
    { "rd:TRICE16_1 line %u (%%u -1)\n",                                                  6024,   2, 16 },
    { "sig:TRICE16_n with 1 to 12 values\n",                                              6800,   0, 32 },
    { "rd:TRICE64 double %e (%%e), aDouble(y)\n",                                         5723,   8, 64 },
    { "dbg:len=%u:",                                                                      7354,   4, 32 },
    { "RD:read         message, SysTick is %6u\n",                                        3455,   4, 32 },
    { "tst:TRICE16_6  %d %d %d %d %d %d\n",                                               1517,  12, 16 },
    { "sig:TRICE64 with variable param count 1 to 12\n",                                  6289,   0, 32 },
    { "rd:TRICE64 %d, %d\n",                                                              3768,  16, 64 },
    { "1",                                                                                6472,   0, 32 },
    { "--------------------------------------------------\n",                             6463,   0, 32 },
    { "att:MyStructEvaluationFunction(json:ExA{Apple:%d, Birn:%u, Fisch:%f}\n",           7582,  12, 32 },
    { "wrn:TRICE_UARTA Character Match Flag is set\n",                                    2270,   0, 32 },
    { "rd:TRICE32_1 line %d (%%d)\n",                                                     1169,   4, 32 },
    { "rd:TRICE16 %p, %p, %p, %p, %p, %p, %p, %p, %p, %p, %p\n",                          2528,  22, 16 },
    { "sig:String or byte slice (quote, indent, hex)\n",                                  1972,   0, 32 },
    { "\n",                                                                               2822,   0, 32 },
    { "DIA:diagnostics message, SysTick is %6u\n",                                        7346,   4, 32 },
    { "tst:TRICE8   %%4d -> %4d %4d %4d %4d\n",                                           6631,   4,  8 },
    { "tst:TRICE32 %%09x ->      %09x      %09x       %09x     %09x\n",                   2836,  16, 32 },
    { "rd:TRICE32 float %E (%%E)\n",                                                      1129,   4, 32 },
    { "wr:TRICE_UARTB Transmission Complete Flag is set\n",                               4022,   0, 32 },
    { "wrn:TRICE_UARTA CTS Flag is set\n",                                                4643,   0, 32 },
    { "DEFAULT:off\n",                                                                    7227,   0, 32 },
    { "rd:TRICE32_12 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                   7438,  48, 32 },
    { "rd:TRICE64 %d, %d, %d, %d, %d, %d\n",                                              1777,  48, 64 },
    { "tst:TRICE32_3  %d %d %d\n",                                                        2072,  12, 32 },
    { "att: Trice 2x half buffer size:%4u ",                                              3965,   4, 32 },
    { "tst:TRICE16_3 %u %u %u\n",                                                         7606,   6, 16 },
    { "rd: \"café\" 		%q	 	Quoted string\n",                                             3777,  -1,  8 },
    { "rd:TRICE8 %d, %d, %d, %d, %d\n",                                                   6626,   5,  8 },
    { "tst:TRICE8 %d %d %d %d %d %d %d %d %d %d\n",                                       2100,  10,  8 },
    { "err:%d timing errors 64-bit\n",                                                    4065,   4, 32 },
    { "rd:TRICE32_6 %d, %d, %d, %d, %d, %d\n",                                            5869,  24, 32 },
    { "msg:%s\n",                                                                         2032,  -2,  8 },
    { "inf: Tryout tx struct:",                                                           5410,   0, 32 },
    { "sig:TRICE8 with variable param count 1 to 12\n",                                   1630,   0, 32 },
    { "tim:TRICE START time message\n",                                                   7306,   0, 32 },
    { "tim:TRICE STOP time message\n",                                                    1898,   0, 32 },
    { "s:     NUCLEO-F030R8     TRICE_MODE %3u     \n",                                   2473,   1,  8 },
    { "MSG: ✅ STOP  select = %d, TriceDepthMax =%4u of %d\n",                           4576,   6, 16 },
    { "rd:TRICE16 %X\n",                                                                  2057,   2, 16 },
    { "rd:TRICE64_4 %d, %d, %d, %d\n",                                                    2205,  32, 64 },
    { "dbg:len=%u:",                                                                      7063,   4, 32 },
    { "rd: 123.456000		%f 	%%f Decimal point, no exponent\n",                             6452,   8, 64 },
    { "sig:TRICE32 with variable param count 1 to 12\n",                                  7422,   0, 32 },
    { "rd:TRICE float %-9f (%%9f)\n",                                                     4069,   0, 32 },
    { "tme:blue+i:blue+h\n",                                                              2521,   0, 32 },
    { "notice:blue:white+h\n",                                                            5163,   0, 32 },
    { "rd:TRICE64_2 %d, %d\n",                                                            7544,  16, 64 },
    { "tst:TRICE64 %%09x ->      %09x      %09x       %09x     %09x\n",                   6724,  32, 64 },
    { "tst:TRICE32_4 %d %d %d %d\n",                                                      5439,  16, 32 },
    { "dbg:\a\aHi!\n",                                                                    3715,   0, 32 },
    { "MSG:triceFifoDepthMax = %d of max %d, triceStreamBufferDepthMax = %d of max %d\n", 5031,  16, 32 },
    { "a:c",                                                                              4048,   0, 32 },
    { "tst:TRICE16 %d %d %d %d %d %d %d\n",                                               2019,  14, 16 },
    { "READ:black+i:yellow+h\n",                                                          7322,   0, 32 },
    { "rd:TRICE64 %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                                  2565,  72, 64 },
    { "tst:TRICE32_2 %x %x\n",                                                            4596,   8, 32 },
    { "rd: 17 	%o 	Base 8\n",                                                             3192,   4, 32 },
    { "sig:Colors and ticks\n",                                                           3564,   0, 32 },
    { "3",                                                                                5268,   0, 32 },
    { "tst:TRICE8_9 %t %b %x %X %d %u %o %O %p\n",                                        3353,   9,  8 },
    { "rd:TRICE float %+9f (%%9f)\n",                                                     3683,   0, 32 },
    { "rd:TRICE32 float %12.6f (%%12.6f)\n",                                              4865,   4, 32 },
    { "rd:TRICE32 float %12.6g (%%12.6g)\n",                                              7560,   4, 32 },
    { "s:     NUCLEO-F411RE     TRICE_MODE %3u     \n",                                   5952,   1,  8 },
    { "rd:TRICE64 double %12.6f (%%12.6f), aDouble(y)\n",                                 5603,   8, 64 },
    { "err:TRICE_UARTB Receiver Time Out Flag is set\n",                                  7321,   0, 32 },
    { "wrn:TRICE_UARTA Receive Wake Up from mute mode Flag is set\n",                     6825,   0, 32 },
    { "msg:x = %g = %d.%03d, %d.%03d\n",                                                  2392,  20, 32 },
    { "debug:130+i\n",                                                                    3148,   0, 32 },
    { "rd:TRICE64 %d, %d\n",                                                              4889,  16, 64 },
    { "tim: pre TriceDecryption SysTick=%d\n",                                            4887,   2, 16 },
    { "rd:TRICE %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                                    2232,  36, 32 },
    { "tst:TRICE16 %d %d %d %d %d %d\n",                                                  4792,  12, 16 },
    { "tst:TRICE8   %%4o -> %4o %4o %4o %4o\n",                                           6179,   4,  8 },
    { "tst:TRICE8_3 %d %d %d\n",                                                          4080,   3,  8 },
    { "rd:TRICE32_1 float %G (%%G)\n",                                                    2156,   4, 32 },
    { "wrn:TRICE_UARTA CTS interrupt Flag is set\n",                                      3876,   0, 32 },
    { "s:     NUCLEO-G031K8     TRICE_MODE %3u     \n",                                   7374,   1,  8 },
    { "tst:TRICE8_7 %02x %02x %02x %02x %02x %02x %02x\n",                                3839,   7,  8 },
    { "wr:TRICE_UARTB Transmit Enable Acknowledge Flag is set\n",                         1843,   0, 32 },
    { "TRACE:default+i:default+h\n",                                                      3159,   0, 32 },
    { "tst:TRICE8_8 %02x %02x %02x %02x %02x %02x %02x %02x\n",                           2938,   8,  8 },
    { "rd:TRICE32 float %G (%%G)\n",                                                      3584,   4, 32 },
    { "MSG: 💚 START select = %d\n",                                                    5350,   2, 16 },
    { "1/11 = %g\n",                                                                      2623,   4, 32 },
    { "inf:rx:USART1 rx:",                                                                6877,   0, 32 },
    { "err:st64=%d < st64_1=%d\n",                                                        7408,  16, 64 },
    { "msg:Sending array: %s\n",                                                          5983,  -1,  8 },
    { "wrn:TRICE_UARTA IDLE line detected Flag is set\n",                                 6534,   0, 32 },
    { "rd:TRICE64_1 line %u (%%u)\n",                                                     1058,   8, 64 },
    { "tst:TRICE8_5 %u %u %u %u %u\n",                                                    3556,   5,  8 },
    { "tst:TRICE64 %d %d %d %d %d %d %d %d %d %d %d\n",                                   1853,  88, 64 },
    { "tst:TRICE64_2  %d %d\n",                                                           1711,  16, 64 },
    { "rd:TRICE64 double %E (%%E), aDouble(y)\n",                                         3795,   8, 64 },
    { "MSG: ✅ STOP  select = %d, TriceDepthMax =%4u of %d\n",                           3260,   6, 16 },
    { "wr:d",                                                                             4632,   0, 32 },
    { "err:%d timing errors 64-bit\n",                                                    1352,   4, 32 },
    { "interrupt:magenta+i:default+h\n",                                                  2022,   0, 32 },
    { "rd:TRICE line %E (%%E)\n",                                                         7260,   4, 32 },
    { "rd: 123.46	 		%.2f		%%.2f Default width, precision 2\n",                           7773,   4, 32 },
    { "tst:TRICE16_7  %d %d %d %d %d %d %d\n",                                            1963,  14, 16 },
    { "rd:TRICE8_3 %d, %d, %d\n",                                                         2618,   3,  8 },
    { "tst:TRICE8_6 %d %d %d %d %d %d\n",                                                 4666,   6,  8 },
    { "rd:TRICE float %+9.f (%%9.f)\n",                                                   5078,   0, 32 },
    { "rd:TRICE8_9 %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                                 4028,   9,  8 },
    { "rd:TRICE32 int %d, float %f (%%f), %08x, %032b\n",                                 7146,  16, 32 },
    { "tst:TRICE32 %d %d %d %d %d %d %d %d\n",                                            3812,  32, 32 },
    { "s:     \n",                                                                        3003,   0, 32 },
    { "sig:TRICE_S=%s\n",                                                                 5129,  -1,  8 },
    { "rd:TRICE32 float %12.6E (%%12.6E)\n",                                              5902,   4, 32 },
    { "tst:TRICE8_1 %02x\n",                                                              7808,   1,  8 },
    { "err:st32=%d < st32_1=%d\n",                                                        2140,   8, 32 },
    { "rd:TRICE16 %p, %p, %p, %p, %p, %p, %p\n",                                          1460,  14, 16 },
    { "rd:TRICE float %+9.6f (%%9.6f)\n",                                                 6915,   0, 32 },
    { "rd:TRICE float %+.9f (%%.9f)\n",                                                   2370,   0, 32 },
    { "rd:TRICE_UARTA Receive Enable Acknowledge Flag is set\n",                          4203,   0, 32 },
    { "rd:TRICE64 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                          4096,  88, 64 },
    { "\n",                                                                               7721,   0, 32 },
    { "1/11 = %g\n",                                                                      1570,   4, 32 },
    { "rd:TRICE8_6 %d, %d, %d, %d, %d, %d\n",                                             5101,   6,  8 },
    { "rd:TRICE32 %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                                  1247,  36, 32 },
    { "tst:TRICE8  %%03x -> %03x  %03x  %03x  %03x\n",                                    5316,   4,  8 },
    { "tst:TRICE8 %d %d %d %d %d %d\n",                                                   3060,   6,  8 },
    { "rd:TRICE8 %d, %d, %d, %d, %d, %d, %d\n",                                           4819,   7,  8 },
    { "tst:TRICE16_1 %u\n",                                                               2982,   2, 16 },
    { "tst:TRICE8_10 %d %d %d %d %d %d %d %d %d %d\n",                                    3609,  10,  8 },
    { "rd:TRICE float %-f (%%f)\n",                                                       7483,   0, 32 },
    { "signal:118+i\n",                                                                   6837,   0, 32 },
    { "diag:f",                                                                           2008,   0, 32 },
    { "tst:TRICE8 %d %d %d %d\n",                                                         7038,   4,  8 },
    { "a:c",                                                                              5877,   0, 32 },
    { "tst:TRICE16_1  %d\n",                                                              7036,   2, 16 },
    { "tst:TRICE64 %d %d %d %d %d %d %d %d %d %d\n",                                      7210,  80, 64 },
    { "att:positive and negative float in format variants\n",                             7520,   0, 32 },
    { "err:TRICE_UARTB Framing Error Flag is set\n",                                      5027,   0, 32 },
    { "rd:TRICE16 %X, %X, %X, %X, %X, %X, %X, %X, %X, %X, %X\n",                          1700,  22, 16 },
    { "rd:TRICE64 int %d, double %f (%%f), %016x, %064b\n",                               4835,  32, 64 },
    { "tst:TRICE64 %%10d ->     %10d     %10d     %10d    %10x\n",                        3611,  32, 64 },
    { "rd:TRICE16 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                          6097,  22, 16 },
    { "rd:TRICE32 %d, %d, %d, %d, %d, %d, %d\n",                                          7046,  28, 32 },
    { "sig:Legacy TRICE8\n",                                                              1655,   0, 32 },
    { "dbg:len=%u: ",                                                                     3687,   4, 32 },
    { "att:...done\n",                                                                    2743,   0, 32 },
    { "tst:TRICE32 %d %d %d %d\n",                                                        7262,  16, 32 },
    { "inf:sizeOf(Tryout) = %d, buffer length = %d\n",                                    6337,   8, 32 },
    { "rd:TRICE32 %d, %d, %d, %d\n",                                                      7650,  16, 32 },
    { "tst:TRICE32_1 %08x\n",                                                             1335,   4, 32 },
    { "rd:TRICE_UARTB Receive Enable Acknowledge Flag is set\n",                          7453,   0, 32 },
    { "tst:TRICE32 %d %d %d %d %d %d %d %d %d %d\n",                                      2074,  40, 32 },
    { "tst:TRICE64 %d %d\n",                                                              1969,  16, 64 },
    { "wrn:TRICE_UARTA Receive Wake Up from mute mode Flag is set\n",                     5225,   0, 32 },
    { "dbg:\t\t\tHi!\n",                                                                  7445,   0, 32 },
    { "isr:TRICE isr message, SysTick is %6d\n",                                          1076,   4, 32 },
    { "tst:TRICE8 %d %d %d %d %d %d %d\n",                                                1308,   7,  8 },
    { "rd:TRICE line %u (%%u)\n",                                                         6159,   4, 32 },
    { "rd:TRICE8 line %t (%%t ,2)\n",                                                     1495,   1,  8 },
    { "wrn:TRICE_UARTA CTS Flag is set\n",                                                5220,   0, 32 },
    { "rd:TRICE16_6 %d, %d, %d, %d, %d, %d\n",                                            2009,  12, 16 },
    { "rd:TRICE32 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                      3247,  48, 32 },
    { "rd:TRICE32_3 %d, %d, %d\n",                                                        4958,  12, 32 },
    { "WRN:warning     message, SysTick is %6u\n",                                        6838,   4, 32 },
    { "tst:TRICE8_4 %d %d %d %d\n",                                                       3142,   4,  8 },
    { "sig:%s\n",                                                                         7719,  -1,  8 },
    { "s:     \n",                                                                        7611,   0, 32 },
    { "isr:TRICE isr message, SysTick is %6d\n",                                          7509,   4, 32 },
    { "rd:TRICE64_6 %d, %d, %d, %d, %d, %d\n",                                            6618,  48, 64 },
    { "sig:Character (quoted, Unicode)\n",                                                6720,   0, 32 },
    { "tst:TRICE16 %d %d %d %d\n",                                                        3864,   8, 16 },
    { "tst:TRICE64_12 %d %d %d %d %d %d %d %d %d %d %d %d\n",                             2992,  96, 64 },
    { "rd:TRICE float %-9.6f (%%9.6f)\n",                                                 5261,   0, 32 },
    { "rd:TRICE8 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                               5514,  10,  8 },
    { "rd:TRICE8 %d, %d, %d, %d, %d, %d\n",                                               4356,   6,  8 },
    { "rd:TRICE8_8 %d, %d, %d, %d, %d, %d, %d, %d\n",                                     6625,   8,  8 },
    { "sig:Double (indent, precision, scientific notation)\n",                            7188,   0, 32 },
    { "rd: 123.46			%.2f    	%%.2f Default width, precision 2\n",                         3920,   8, 64 },
    { "rd:TRICE float %9.f (%%9.f)\n",                                                    6833,   4, 32 },
    { "rd:TRICE float %f (%%f)\n",                                                        6756,   4, 32 },
    { "rd:TRICE8_1 %d\n",                                                                 4793,   1,  8 },
    { "dbg:len=%u: ",                                                                     3009,   4, 32 },
    { "rd:TRICE16_1 line %x (%%x -1)\n",                                                  2415,   2, 16 },
    { "wr:TRICE_UARTA Transmission Complete Flag is set\n",                               2824,   0, 32 },
    { "tst:TRICE8_5 %02x %02x %02x %02x %02x\n",                                          2358,   5,  8 },
    { "rd:TRICE64 double %E (%%E), aDouble(y)\n",                                         5874,   8, 64 },
    { "err:TRICE_UARTA Framing Error Flag is set\n",                                      7172,   0, 32 },
    { "att:Executing command %s ...\n",                                                   3193,  -1,  8 },
    { "rd:TRICE64_12 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                   4982,  96, 64 },
    { "message:J",                                                                        1555,   0, 32 },
    { "rd:Use %%p to format a pointer in base 16 notation with leading 0x. (%p)\n",       4532,   2, 16 },
    { "rd:TRICE32 int %d, float %f (%%f), %08x, %032b\n",                                 2105,  16, 32 },
    { "s:     ",                                                                          2966,   0, 32 },
    { "\n",                                                                               5258,   0, 32 },
    { "alarm:red+i:white+h\n",                                                            5118,   0, 32 },
    { "rd:TRICE16_7 %d, %d, %d, %d, %d, %d, %d\n",                                        1805,  14, 16 },
    { "tst:TRICE8 %d %d\n",                                                               6003,   2,  8 },
    { "err:TRICE_UARTA Receiver Time Out Flag is set\n",                                  2215,   0, 32 },
    { "VERBOSE:blue:default\n",                                                           1800,   0, 32 },
    { "tst:TRICE8_4  %d %d %d %d\n",                                                      3603,   4,  8 },
    { "err:TRICE_UARTB Parity Error Flag is set\n",                                       6945,   0, 32 },
    { "d:Sending uint16 counter as two byte hex: %x\n",                                   1645,   2, 16 },
    { "tst:TRICE32_1 %u\n",                                                               2495,   4, 32 },
    { "tst:TRICE16_3  %d %d %d\n",                                                        6391,   6, 16 },
    { "tst:TRICE16_9  %d %d %d %d %d %d %d %d %d\n",                                      7688,  18, 16 },
    { "rd:TRICE8 line %o (%%o ,-1)\n",                                                    7395,   1,  8 },
    { "inf:TRICE_UARTA Busy Flag is set\n",                                               3236,   0, 32 },
    { "ALARM:red+i:white+h\n",                                                            7304,   0, 32 },
    { "rd:TRICE64 %d, %d\n",                                                              2746,  16, 64 },
    { "tst:TRICE64_2 %d %d\n",                                                            5308,  16, 64 },
    { "tst:TRICE16 %d %d %d %d %d %d %d %d %d %d %d %d\n",                                6057,  24, 16 },
    { "tst:TRICE32 %d %d %d\n",                                                           6899,  12, 32 },
    { "s:                                          \n",                                   2534,   0, 32 },
    { "sig:With TRICE_N:%s\n",                                                            3769,  -2,  8 },
    { "sig:TRICE_N=%s\n",                                                                 5182,  -2,  8 },
    { "rd:TRICE32 %d, %d, %d, %d, %d\n",                                                  7629,  20, 32 },
    { "rd:TRICE64_10 %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",                           1417,  80, 64 },
    { "tst:TRICE64 %d %d %d %d %d\n",                                                     4822,  40, 64 },
    { "rd:TRICE float %f (%%f)\n",                                                        6447,   4, 32 },
    { "SIGNAL:118+i\n",                                                                   7224,   0, 32 },
    { "att: Trice stream buffer size:%5u ",                                               1135,   4, 32 },
    { "WARNING:USARTq OverRun Error Flag is set!\n",                                      6470,   0, 32 },
    { "ALERT:magenta:magenta+h\n",                                                        1296,   0, 32 },
    { "tim:TRICE --------------------------------------------------\n",                   7842,   0, 32 },
    { "--------------------------------------------------\n",                             3703,   0, 32 },
    { "rd:TRICE32_1 line %X (%%X)\n",                                                     4680,   4, 32 },
    { "tst:TRICE16   %%6d ->  %6d  %6d  %6d  %6d\n",                                      5248,   8, 16 },
    { "tst:TRICE16_4  %d %d %d %d\n",                                                     1661,   8, 16 },
    { "rd:TRICE float %F (%%F)\n",                                                        5290,   4, 32 },
    { "err:%d timing errors 32-bit\n",                                                    6479,   4, 32 },
    { "wrn:TRICE_UARTA IDLE line detected Flag is set\n",                                 3332,   0, 32 },
};

//! triceFormatStringListElements holds the compile time computed count of list elements.
const unsigned triceFormatStringListElements = sizeof(triceFormatStringList) / sizeof(triceFormatStringList_t);
