// SPDX-License-Identifier: MIT

// Package decoder provides several decoders for differently encoded trice streams.
package decoder

import (
	"encoding/binary"
	"fmt"
	"io"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/rokath/trice/internal/emitter"
	"github.com/rokath/trice/internal/fmtspec"
	"github.com/rokath/trice/internal/id"
)

// TestTable is a struct slice generated by the trice tool -testTable option.
type TestTable []struct {
	In  []byte // byte buffer sequence
	Exp string // output
}

const (

	// LittleEndian is true for little endian trice data.
	LittleEndian = true

	// BigEndian is the flag value for target endianness.
	BigEndian = false

	// defaultSize is the beginning receive and sync buffer size.
	DefaultSize = 64 * 1024

	// hints is the help information in case of errors.
	Hints = "att:Hints:Baudrate? Encoding? Interrupt? Overflow? Parameter count? Format specifier? Password? til.json? Version?"

	UnsignedFormatSpecifier = 0 // %u -> %d
	SignedFormatSpecifier   = 1 // signed integer formatting
	FloatFormatSpecifier    = 2 // %f and relatives
	BooleanFormatSpecifier  = 3 // a %t (bool) found
	PointerFormatSpecifier  = 4 // a %p (pointer) found
	StringFormatSpecifier   = 5 // a %s found

	// LiFmtDefault is the default layout for location info (file and line).
	LiFmtDefault = "info:%21s%6d "
)

var (
	// Verbose gives more information on output if set. The value is injected from main packages.
	Verbose bool

	// ShowID is used as format string for displaying the first trice ID at the start of each line if not "".
	ShowID string

	// decoder.LastTriceID is last decoded ID. It is used for switch -showID.
	LastTriceID id.TriceID

	// TestTableMode is a special option for easy decoder test table generation.
	TestTableMode bool

	// Unsigned if true, forces hex and in values printed as unsigned values.
	Unsigned bool

	DebugOut                        = false        // DebugOut enables debug information.
	DumpLineByteCount               int            // DumpLineByteCount is the bytes per line for the dumpDec decoder.
	InitialCycle                    = true         // InitialCycle helps with automatic cycle counter checks.
	TargetTimestamp                 uint64         // targetTimestamp contains target specific timestamp value.
	TargetTimestampSize             int            // TargetTimestampSize is set in dependence of trice type.
	TargetLocation                  uint32         // targetLocation contains 16 bit file id in high and 16 bit line number in low part.
	TargetStamp                     string         // TargetTimeStampUnit is the target timestamps time base for default formatting.
	TargetStamp32                   string         // ShowTargetStamp32 is the format string for target timestamps.
	TargetStamp16                   string         // ShowTargetStamp16 is the format string for target timestamps.
	TargetStamp0                    string         // ShowTargetStamp0 is the format string for target timestamps.
	TargetStamp32Delta              string         // TargetStamp32Delta is the format string for 32-bit target timestamp deltas.
	TargetStamp16Delta              string         // TargetStamp16Delta is the format string for 16-bit target timestamp deltas.
	TargetStamp0Delta               string         // TargetStamp0Delta is the format string for delta column alignment without target timestamps.
	TargetTimeStampUnitPassed       bool           // TargetTimeStampUnitPassed is true when flag was TargetTimeStampUnit passed.
	ShowTargetStamp32Passed         bool           // ShowTargetStamp32Passed is true when flag was TargetTimeStamp32 passed.
	ShowTargetStamp16Passed         bool           // ShowTargetStamp16Passed is true when flag was TargetTimeStamp16 passed.
	ShowTargetStamp0Passed          bool           // ShowTargetStamp0Passed is true when flag was TargetTimeStamp0 passed.
	ShowTargetStamp32DeltaPassed    bool           // ShowTargetStamp32DeltaPassed is true when flag TargetStamp32Delta was passed.
	ShowTargetStamp16DeltaPassed    bool           // ShowTargetStamp16DeltaPassed is true when flag TargetStamp16Delta was passed.
	ShowTargetStamp0DeltaPassed     bool           // ShowTargetStamp0DeltaPassed is true when flag TargetStamp0Delta was passed.
	LocationInformationFormatString = LiFmtDefault // LocationInformationFormatString is the format string for target location: line number and file name.
	LiFmtDefaultLen                 int            // Compute as var from LocationInformationFormatString.
	TargetLocationExists            bool           // TargetLocationExists is set in dependence of p.COBSModeDescriptor. (obsolete)
	PackageFraming                  string         // Framing is used for packing. Valid values COBS, TCOBS, TCOBSv1 (same as TCOBS)
	IDBits                          = 14           // IDBits holds count of bits used for ID (used at least in trexDecoder)
	NewlineIndent                   = -1           // Used for trice messages containing several newlines in format string for formatting.
	TriceStatistics                 bool           // Keep the occurred count for each Trice log when Trice is closed.
	IDStat                          map[id.TriceID]int
)

func init() {
	IDStat = make(map[id.TriceID]int)
	LiFmtDefaultLen = locationInformationWidth()
}

// New abstracts the function type for a new decoder.
type New func(out io.Writer, lut id.TriceIDLookUp, m *sync.RWMutex, li id.TriceIDLookUpLI, in io.Reader, endian bool) Decoder

// Config contains common constructor parameters for all decoders.
type Config struct {
	Out         io.Writer
	LUT         id.TriceIDLookUp
	LUTMutex    *sync.RWMutex
	LI          id.TriceIDLookUpLI
	In          io.Reader
	Endian      bool
	NeedBuffers bool // NeedBuffers allocates B, B0 and InnerBuffer for framed decoders.
}

// Decoder is providing a byte reader returning decoded trice's.
// SetInput allows switching the input stream to a different source.
type Decoder interface {
	io.Reader
	SetInput(io.Reader)
}

// DecoderData is the common data struct for all decoders.
type DecoderData struct {
	W           io.Writer          // io.Stdout or the like
	In          io.Reader          // in is the inner reader, which is used to get raw bytes
	InnerBuffer []byte             // avoid repeated allocation (trex)
	IBuf        []byte             // iBuf holds unprocessed (raw) bytes for interpretation.
	B           []byte             // read buffer holds a single decoded TCOBS package, which can contain several trices.
	B0          []byte             // initial value for B
	Endian      bool               // endian is true for LittleEndian and false for BigEndian
	TriceSize   int                // trice head and payload size as number of bytes
	ParamSpace  int                // trice payload size after head
	SLen        int                // string length for TRICE_S
	Lut         id.TriceIDLookUp   // id look-up map for translation
	LutMutex    *sync.RWMutex      // to avoid concurrent map read and map write during map refresh triggered by filewatcher
	Li          id.TriceIDLookUpLI // location information map
	Trice       id.TriceFmt        // id.TriceFmt // received trice
}

// NewDecoderData initializes the common base fields for a decoder.
//
// Callers can request pre-allocated internal working buffers with NeedBuffers.
func NewDecoderData(c Config) DecoderData {
	if c.Out == nil {
		c.Out = io.Discard
	}
	if c.LUTMutex == nil {
		c.LUTMutex = new(sync.RWMutex)
	}
	d := DecoderData{
		W:        c.Out,
		In:       c.In,
		IBuf:     make([]byte, 0, DefaultSize),
		Endian:   c.Endian,
		Lut:      c.LUT,
		LutMutex: c.LUTMutex,
		Li:       c.LI,
	}
	if c.NeedBuffers {
		d.B = make([]byte, 0, DefaultSize)
		d.B0 = make([]byte, DefaultSize)
		d.InnerBuffer = make([]byte, DefaultSize)
	}
	return d
}

// SetInput allows switching the input stream to a different source.
//
// This function is for easier testing with cycle counters.
func (p *DecoderData) SetInput(r io.Reader) {
	p.In = r
}

// ReadU16 returns the 2 b bytes as uint16 according the specified endianness
func (p *DecoderData) ReadU16(b []byte) uint16 {
	if p.Endian {
		return binary.LittleEndian.Uint16(b)
	}
	return binary.BigEndian.Uint16(b)
}

// ReadU32 returns the 4 b bytes as uint32 according the specified endianness
func (p *DecoderData) ReadU32(b []byte) uint32 {
	if p.Endian {
		return binary.LittleEndian.Uint32(b)
	}
	return binary.BigEndian.Uint32(b)
}

// ReadU64 returns the 8 b bytes as uint64 according the specified endianness
func (p *DecoderData) ReadU64(b []byte) uint64 {
	if p.Endian {
		return binary.LittleEndian.Uint64(b)
	}
	return binary.BigEndian.Uint64(b)
}

// UReplaceN checks all format specifier in i and replaces %nu with %nd and returns that result as o.
//
// If a replacement took place on position k u[k] is 0. Afterwards len(u) is amount of found format specifiers.
// Additional, if UnsignedHex is true, for FormatX specifiers u[k] is also 1.
// If a float format specifier was found at position k, u[k] is 2,
// http://www.cplusplus.com/reference/cstdio/printf/
// https://www.codingunit.com/printf-format-specifiers-format-conversions-and-formatted-output
func UReplaceN(i string) (o string, u []int) {
	// Normalize valid C length modifiers first so that both the source scanner and
	// the runtime decoder share the same understanding. This fixes Issue #649 and
	// related %l... cases without changing the original format string stored in til.json.
	o, specs := fmtspec.Normalize(i)
	for _, spec := range specs {
		switch spec.Kind {
		case fmtspec.KindPointer:
			// This would require `unsafe.Pointer(uintptr(n))` inside unSignedOrSignedOut.
			// There are false positive windows vet warnings:
			// https://stackoverflow.com/questions/43767898/casting-a-int-to-a-pointer
			// https://github.com/golang/go/issues/41205
			// As workaround replace %p with %x in the format strings.
			o = replaceNextConversion(o, 'p', 'x')
			u = append(u, PointerFormatSpecifier)
		case fmtspec.KindBool:
			u = append(u, BooleanFormatSpecifier)
		case fmtspec.KindString:
			u = append(u, StringFormatSpecifier)
		case fmtspec.KindFloat:
			u = append(u, FloatFormatSpecifier)
		case fmtspec.KindUnsigned:
			// Keep the longstanding Trice behavior: Go fmt prints unsigned payloads
			// via %d while the decoder chooses an unsigned Go integer type below.
			o = replaceNextConversion(o, 'u', 'd')
			u = append(u, UnsignedFormatSpecifier)
		case fmtspec.KindBasedInteger:
			// Keep `%d`/`%i` signed even when -unsigned is active. The historical
			// `Unsigned` switch only affected the base-changing integer verbs handled
			// by the old locX branch (%x/%X/%o/%O/%b/...). Issue #649 added the shared
			// parser, but this behavior must stay intact to avoid changing `%d` into
			// an unsigned decimal print, as seen in the intensive PC target tests.
			if Unsigned {
				u = append(u, UnsignedFormatSpecifier)
			} else {
				u = append(u, SignedFormatSpecifier)
			}
		case fmtspec.KindSigned:
			u = append(u, SignedFormatSpecifier)
		}
	}
	return
}

func replaceNextConversion(format string, from, to byte) string {
	for i := 0; i < len(format); i++ {
		if format[i] != '%' {
			continue
		}
		if i+1 < len(format) && format[i+1] == '%' {
			i++
			continue
		}
		for j := i + 1; j < len(format); j++ {
			if format[j] == from {
				return format[:j] + string(to) + format[j+1:]
			}
			if isASCIIAlpha(format[j]) {
				break
			}
		}
	}
	return format
}

func isASCIIAlpha(b byte) bool {
	return ('a' <= b && b <= 'z') || ('A' <= b && b <= 'Z')
}

// Dump prints the byte slice as hex in one line
func Dump(w io.Writer, b []byte) {
	for _, x := range b {
		fmt.Fprintf(w, "%02x ", x)
	}
	fmt.Fprintln(w, "")
}

func RecordForStatistics(tid id.TriceID) {
	if !TriceStatistics && !emitter.AllStatistics {
		return
	}
	count := IDStat[tid]
	count++
	IDStat[tid] = count
}

var (
	IDLUT id.TriceIDLookUp
	LILUT id.TriceIDLookUpLI
)

func PrintTriceStatistics(w io.Writer) {
	if !TriceStatistics && !emitter.AllStatistics {
		return
	}
	var sum int
	fmt.Fprintf(w, "\nTrice Statistics:                  (n: Trice ends with no newline, if 0 ↴)\n\n")
	fmt.Fprintln(w, `   Count |       Location Information       | Line |  ID   |    Type    |n| Format String`)
	fmt.Fprintln(w, " ------- | -------------------------------- | ---- | ----- | ---------- |-|----------------------------------------")
	for tid, count := range IDStat {
		sum += count
		trice := IDLUT[tid]
		li := LILUT[tid]
		var found bool
		trice.Strg, found = strings.CutSuffix(trice.Strg, `\n`)
		newline := ` `
		if !found {
			newline = `0`
		}
		file := id.ToLIPath(li.File)
		fmt.Fprintf(w, "%8d | %32s |%5d | %5d | %10s |%s| %s\n", count, file, li.Line, tid, trice.Type, newline, emitter.Colorize(trice.Strg))
	}
	fmt.Fprintln(w, " ------------------------------------------------------------------------------------------------------------------")
	fmt.Fprintf(w, "%8d Trice messsges\n", sum)
}

// LocationInformation returns optional location information for id.
func LocationInformation(tid id.TriceID, li id.TriceIDLookUpLI) string {
	if li != nil && LocationInformationFormatString != "off" && LocationInformationFormatString != "none" {
		if li, ok := li[tid]; ok {
			return fmt.Sprintf(LocationInformationFormatString, filepath.Base(li.File), li.Line)
		} else {
			return fmt.Sprintf(LocationInformationFormatString, "", 0)
		}
	} else {
		if Verbose {
			return "no li"
		}
	}
	return ""
}

// locationInformationWidth computes byte count for location information.
func locationInformationWidth() (sum int) {
	re := regexp.MustCompile("[0-9]+")
	s := re.FindAllString(LocationInformationFormatString, -1)
	for _, n := range s {
		v, err := strconv.Atoi(n)
		if err != nil {
			panic(err)
		}
		sum += v
	}
	return sum + 1 // plus space after line number
}

// CorrectWrappedTimestamp checks whether a 32-bit timestamp falls outside the valid range
// and virtually sets a 33rd bit by adding 2^32 seconds to it
func CorrectWrappedTimestamp(ts32 uint32) time.Time {

	const (
		minValidYear = 2000
		maxValidYear = 2038
		wrapOffset   = 1 << 32 // 2^32 seconds
	)

	// Interpret the timestamp as time.Time
	t := time.Unix(int64(ts32), 0).UTC()

	if t.Year() >= minValidYear && t.Year() <= maxValidYear {
		return t
	}

	// Apply wraparound correction by adding 2^32 seconds
	tWrapped := time.Unix(int64(ts32)+wrapOffset, 0).UTC()

	// If the corrected timestamp is plausible, return it
	if tWrapped.Year() > maxValidYear && tWrapped.Year() <= maxValidYear+100 {
		return tWrapped
	}

	// Fallback: return the original timestamp and print a warning
	fmt.Printf("WARNING: Timestamp %v (%d) is outside the expected year range\n", t, ts32)
	return t
}
