// SPDX-License-Identifier: MIT

#include <stdio.h>
#if defined(_WIN32)
#include <windows.h>
#else
#include <sys/time.h>
#endif
#include "trice.h"
// `trice bind` creates this include and its header; source code keeps no numeric Trice IDs.
#include "trice_main_c_K50434C4F4744454D.h" // trice-bind: keep as last include before this file's Trice calls
static void writeLocalLog(const char*, size_t);
static int stampPrefix(char*, size_t, uint16_t, uint8_t, uint32_t);
#define PC_LOG_TEXT_SIZE 512u // Bounds one record and its UTF-16 console copy.
#define TRICE_CHECK_SCAN_END 3200

// drainLocalLog consumes every complete record generated by one TriceCheck
// index. Draining after each index prevents a deliberately bursty test case
// from accumulating together with later cases in the ring buffer.
static int drainLocalLog(char* text, size_t textSize, int triceCheckIndex) {
	int length;
	while ((length = TriceLog(text, textSize)) > 0) {
		writeLocalLog(text, (size_t)length);
	}
	if (length < 0) {
		fprintf(stderr, "TriceLog failed for TriceCheck index %d: %d\n", triceCheckIndex, length);
		return -1;
	}
	return 0;
}

int main(void) {
	char text[PC_LOG_TEXT_SIZE];
	const uint16_t samples[] = {1u, 0x2au, 0x1234u};

	// The standard C library snprintf supplies the formatter hook contract.
	UserTriceLogPrintfFn = snprintf;
	UserTriceLogPrefixFn = stampPrefix;
	trice("msg:PC local log is running\n");
	trice("value=%d hex=%08x\n", -42, 0x2a);
	triceS("text:runtime=[%s]\n", "hello from triceS");
	triceS("text:width and precision=[%-12.5s]\n", "abcdefgh");
	trice32("float:single=%+.3f scientific=%.2e\n", aFloat(3.125f), aFloat(-0.03125f));
	trice64("float:double=%.9f compact=%.6g\n", aDouble(3.141592653589793), aDouble(123456.0));
	trice8("special:binary=%#b bool=%t octal=%O pointer=%p quoted=%q\n", 5u, 1u, 9u, 0xabu, 'A');
	triceS("text:quoted=%q\n", "line 1\n\"line 2\"");
	TRICE16_B("buffer:%04x \n", samples, sizeof(samples) / sizeof(samples[0]));

	if (drainLocalLog(text, sizeof(text), 0) < 0) {
		return 1;
	}

	// Exercise the same producer corpus used by the normal Trice target tests.
	// Unsupported non-log families are excluded by this target's configuration;
	// every record produced here is expected to be locally printable.
	for (int index = 0; index <= TRICE_CHECK_SCAN_END; ++index) {
		TriceCheck(index);
		if (drainLocalLog(text, sizeof(text), index) < 0) {
			return 1;
		}
	}
	return 0;
}
static int localLogLineStart = 1; // Keeps record prefixes aligned with logical output lines.
// TriceDemoMilliseconds returns elapsed demo time. Unsigned subtraction makes
// the Windows tick-count wrap well-defined; the POSIX fallback restarts at zero
// if an external wall-clock correction moves the clock backwards.
uint32_t TriceDemoMilliseconds(void) {
#if defined(_WIN32)
	static DWORD firstTick;
	static int initialized;
	DWORD currentTick = GetTickCount();
	if (initialized == 0) {
		firstTick = currentTick;
		initialized = 1;
	}
	return (uint32_t)(currentTick - firstTick);
#else
	static uint64_t firstMilliseconds;
	static int initialized;
	struct timeval currentTime;
	if (gettimeofday(&currentTime, NULL) != 0) {
		return 0u;
	}
	uint64_t currentMilliseconds = (uint64_t)currentTime.tv_sec * 1000u + (uint64_t)currentTime.tv_usec / 1000u;
	if (initialized == 0 || currentMilliseconds < firstMilliseconds) {
		firstMilliseconds = currentMilliseconds;
		initialized = 1;
	}
	return (uint32_t)(currentMilliseconds - firstMilliseconds);
#endif
}

// TriceDemoMicrosecondOffset mirrors the free-running 0...999 us TIM17 stamp
// used by G0B1_inst. Only the position inside the current millisecond matters.
uint16_t TriceDemoMicrosecondOffset(void) {
#if defined(_WIN32)
	LARGE_INTEGER counter;
	LARGE_INTEGER frequency;
	if (QueryPerformanceCounter(&counter) == 0 || QueryPerformanceFrequency(&frequency) == 0 || frequency.QuadPart <= 0) {
		return 0u;
	}
	return (uint16_t)(((uint64_t)(counter.QuadPart % frequency.QuadPart) * 1000000u / (uint64_t)frequency.QuadPart) % 1000u);
#else
	struct timeval currentTime;
	if (gettimeofday(&currentTime, NULL) != 0) {
		return 0u;
	}
	return (uint16_t)((uint32_t)currentTime.tv_usec % 1000u);
#endif
}

// writeLocalLog bypasses narrow Windows console conversion. Real consoles get
// UTF-16; pipes and redirected files keep the original UTF-8 bytes.
static void writeLocalLog(const char* text, size_t length) {
	if (length != 0u) {
		localLogLineStart = text[length - 1u] == '\n' || text[length - 1u] == '\r';
	}
#if defined(_WIN32)
	HANDLE output = GetStdHandle(STD_OUTPUT_HANDLE);
	if (output != NULL && output != INVALID_HANDLE_VALUE) {
		DWORD consoleMode;
		if (length <= PC_LOG_TEXT_SIZE && GetConsoleMode(output, &consoleMode) != 0) {
			wchar_t wide[PC_LOG_TEXT_SIZE];
			int wideLength = MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, text, (int)length, wide, PC_LOG_TEXT_SIZE);
			DWORD written;
			if (wideLength > 0 && WriteConsoleW(output, wide, (DWORD)wideLength, &written, NULL) != 0) {
				return;
			}
		}
		DWORD written;
		(void)WriteFile(output, text, (DWORD)length, &written, NULL);
		return;
	}
#endif
	(void)fwrite(text, 1u, length, stdout);
}

// stampPrefix mirrors the G0B1_inst host presentation at logical line starts.
// Unstamped records retain the same twelve-column alignment as stamped records.
static int stampPrefix(char* buffer, size_t size, uint16_t id, uint8_t stampBits, uint32_t stamp) {
	(void)id;
	if (localLogLineStart == 0) {
		if (size != 0u) {
			buffer[0] = '\0';
		}
		return 0;
	}
	switch (stampBits) {
	case 0u:
		return snprintf(buffer, size, TRICE_LOCAL_LOG_STAMP0_FORMAT " ");
	case 16u: {
		return snprintf(buffer, size,
		                TRICE_LOCAL_LOG_STAMP_COLOR TRICE_LOCAL_LOG_STAMP16_FORMAT TRICE_LOCAL_LOG_STAMP_RESET " ",
		                (unsigned int)(uint16_t)stamp);
	}
	case 32u: {
		uint32_t milliseconds = stamp % 1000u;
		uint32_t totalSeconds = stamp / 1000u;
		uint32_t seconds = totalSeconds % 60u;
		uint32_t totalMinutes = totalSeconds / 60u;
		uint32_t minutes = totalMinutes % 60u;
		uint32_t hours = totalMinutes / 60u;
		return snprintf(buffer, size,
		                TRICE_LOCAL_LOG_STAMP_COLOR TRICE_LOCAL_LOG_STAMP32_FORMAT TRICE_LOCAL_LOG_STAMP_RESET " ",
		                (unsigned long)hours, (unsigned long)minutes, (unsigned long)seconds, (unsigned long)milliseconds);
	}
	default:
		if (size != 0u) {
			buffer[0] = '\0';
		}
		return -1;
	}
}
