// SPDX-License-Identifier: MIT

#include <stdio.h>

#include "trice.h"

// This File Key include is normally inserted once by `trice bind`. The build
// script runs bind before compilation and creates the referenced header below
// build/triceIDs; application code contains no numeric Trice IDs.
#include "trice_main_c_K50434C4F4744454D.h" // trice-bind: keep as last include before this file's Trice calls

// TRICE_CHECK_SCAN_END intentionally exceeds the current physical line count
// of the shared test corpus. TriceCheck uses case __LINE__, so indices without
// a corresponding producer are inexpensive no-ops.
#define TRICE_CHECK_SCAN_END 3200

// drainLocalLog consumes every complete record generated by one TriceCheck
// index. Draining after each index prevents a deliberately bursty test case
// from accumulating together with later cases in the ring buffer.
static int drainLocalLog(char* text, size_t textSize, int triceCheckIndex) {
	int length;
	while ((length = TriceLog(text, textSize)) > 0) {
		(void)fwrite(text, 1u, (size_t)length, stdout);
	}
	if (length < 0) {
		fprintf(stderr, "TriceLog failed for TriceCheck index %d: %d\n", triceCheckIndex, length);
		return -1;
	}
	return 0;
}

int main(void) {
	char text[512];
	const uint16_t samples[] = {1u, 0x2au, 0x1234u};

	// The standard C library snprintf already has the exact hook contract.
	UserTriceLogPrintfFn = snprintf;

	trice("msg:PC local log is running\n");
	trice("value=%d hex=%08x\n", -42, 0x2a);
	triceS("text:runtime=[%s]\n", "hello from triceS");
	triceS("text:width and precision=[%-12.5s]\n", "abcdefgh");
	trice32("float:single=%+.3f scientific=%.2e\n", aFloat(3.125f), aFloat(-0.03125f));
	trice64("float:double=%.9f compact=%.6g\n", aDouble(3.141592653589793), aDouble(123456.0));
	trice8("special:binary=%#b bool=%t octal=%O pointer=%p quoted=%q\n", 5u, 1u, 9u, 0xabu, 'A');
	triceS("text:quoted=%q\n", "line 1\n\"line 2\"");
	TRICE16_B("buffer:%04x \n", samples, sizeof(samples) / sizeof(samples[0]));

	if (drainLocalLog(text, sizeof(text), 0) < 0) {
		return 1;
	}

	// Exercise the same producer corpus used by the normal Trice target tests.
	// Unsupported non-log families are excluded by this target's configuration;
	// every record produced here is expected to be locally printable.
	for (int index = 0; index <= TRICE_CHECK_SCAN_END; ++index) {
		TriceCheck(index);
		if (drainLocalLog(text, sizeof(text), index) < 0) {
			return 1;
		}
	}
	return 0;
}
