// SPDX-License-Identifier: MIT

package id

import (
	"fmt"
	"sort"
	"strings"
)

// renderBindSidecar creates one stable, guard-free descriptor header for a physical owner file.
func renderBindSidecar(plans []bindFilePlan, planIndex int) []byte {
	plan := &plans[planIndex]
	descriptors := append([]bindSiteDescriptor(nil), plan.descriptors...)
	sort.SliceStable(descriptors, func(i, j int) bool {
		if descriptors[i].line != descriptors[j].line {
			return descriptors[i].line < descriptors[j].line
		}
		return descriptors[i].column < descriptors[j].column
	})
	definitions := bindDefinitionSites(plan)
	locations := bindCounterLocationSites(plan)
	regions := append([]bindRebaseRegion(nil), plan.regions...)
	sort.SliceStable(regions, func(i, j int) bool {
		if regions[i].line != regions[j].line {
			return regions[i].line < regions[j].line
		}
		return regions[i].column < regions[j].column
	})

	var builder strings.Builder
	fmt.Fprintf(&builder, "/// \\file %s\n", plan.sidecarName)
	builder.WriteString("/// \\brief Generated by trice bind. Do not edit.\n\n")
	builder.WriteString("// TRICE_INSERT_OFF - Trice parser exclusion marker\n\n")
	if len(regions) > 0 {
		renderBindRebaseModes(&builder, plan)
		builder.WriteString("#else\n\n")
	}
	builder.WriteString("#undef TRICE_BIND_FILE_KEY\n")
	fmt.Fprintf(&builder, "#define TRICE_BIND_FILE_KEY %s\n", plan.key)
	if len(regions) > 0 {
		builder.WriteString("#undef TRICE_BIND_ROUTE_REBASE\n")
		builder.WriteString("#define TRICE_BIND_ROUTE_REBASE(implementation, ...) TRICE_BIND_REBASE_PRODUCT_ROUTE(implementation, __VA_ARGS__)\n")
		builder.WriteString("#undef TRICE_BIND_REBASE_DEFAULT_TID\n")
		fmt.Fprintf(&builder, "#define TRICE_BIND_REBASE_DEFAULT_TID %s\n", bindDefaultWrapper("TRICE"))
	}
	fmt.Fprintf(&builder, "#define TRICE_BIND_ROUTE_%s BIND\n\n", plan.key)
	fmt.Fprintf(&builder, "// -defaultStampSize %d\n", DefaultStampSize)

	for _, site := range definitions {
		fmt.Fprintf(
			&builder,
			"#define %s %du // numeric definition descriptor\n",
			bindDefinitionIDMacroName(plan.key, site),
			site.id,
		)
		fmt.Fprintf(
			&builder,
			"#define %s %s(%s) // %s definition %s\n",
			bindDefinitionMacroName(plan.key, site),
			site.wrapper,
			bindDefinitionIDMacroName(plan.key, site),
			site.definitionName,
			site.comment,
		)
	}
	for _, site := range locations {
		fmt.Fprintf(
			&builder,
			"#define %s %du // numeric counter-selected location descriptor\n",
			bindLocationIDMacroName(plan.key, site),
			site.id,
		)
		fmt.Fprintf(
			&builder,
			"#define %s %s(%s) // counter-selected location %s\n",
			bindLocationMacroName(plan.key, site),
			site.wrapper,
			bindLocationIDMacroName(plan.key, site),
			site.comment,
		)
	}
	if len(definitions)+len(locations) > 0 {
		builder.WriteByte('\n')
	}

	nameWidth, modeWidth, tidWidth := 0, 0, 0
	for _, descriptor := range descriptors {
		site := plans[descriptor.ref.plan].sites[descriptor.ref.site]
		name := bindSiteMacroName(plan.key, descriptor.line)
		tid := bindReferenceTID(plans, descriptor.ref)
		if len(name) > nameWidth {
			nameWidth = len(name)
		}
		if len(site.mode) > modeWidth {
			modeWidth = len(site.mode)
		}
		if len(tid) > tidWidth {
			tidWidth = len(tid)
		}
	}
	for _, descriptor := range descriptors {
		site := plans[descriptor.ref.plan].sites[descriptor.ref.site]
		fmt.Fprintf(
			&builder,
			"#define %-*s %-*s %-*s // %s\n",
			nameWidth,
			bindSiteMacroName(plan.key, descriptor.line),
			modeWidth+1,
			string(site.mode)+",",
			tidWidth,
			bindReferenceTID(plans, descriptor.ref),
			descriptor.comment,
		)
	}
	if len(descriptors) > 0 && len(regions) > 0 {
		builder.WriteByte('\n')
	}
	for _, region := range regions {
		fmt.Fprintf(&builder, "#define TRICE_BIND_REBASE_COUNT_%s %d\n", region.scope, len(region.expansions))
		fmt.Fprintf(&builder, "#define TRICE_BIND_REBASE_AUTO_APPLY_%s(constructor, implementation, index, ...) do { ", region.scope)
		for ordinal, ref := range region.expansions {
			if ordinal > 0 {
				builder.WriteString("else ")
			}
			fmt.Fprintf(
				&builder,
				"if ((index) == %d) { implementation(constructor(%s), __VA_ARGS__); } ",
				ordinal,
				bindReferenceIDMacro(plans, ref),
			)
		}
		builder.WriteString("} while (0)\n")
	}
	if len(regions) > 0 {
		builder.WriteString("\n#endif // generated rebase include mode\n")
	}
	return []byte(builder.String())
}

// bindDefinitionSites returns stable source order for wrapper-owned logical sites.
func bindDefinitionSites(plan *bindFilePlan) []bindSite {
	var sites []bindSite
	for _, site := range plan.sites {
		if site.definitionName != "" {
			sites = append(sites, site)
		}
	}
	sort.SliceStable(sites, func(i, j int) bool {
		if sites[i].line != sites[j].line {
			return sites[i].line < sites[j].line
		}
		return sites[i].column < sites[j].column
	})
	return sites
}

// bindCounterLocationSites returns direct sites whose line-only descriptor is replaced by a rebase map.
func bindCounterLocationSites(plan *bindFilePlan) []bindSite {
	var sites []bindSite
	for _, site := range plan.sites {
		if site.definitionName == "" && site.counterSelected {
			sites = append(sites, site)
		}
	}
	sort.SliceStable(sites, func(i, j int) bool {
		if sites[i].line != sites[j].line {
			return sites[i].line < sites[j].line
		}
		return sites[i].column < sites[j].column
	})
	return sites
}

// bindDefinitionMacroName gives every inner wrapper site a compile-time descriptor.
func bindDefinitionMacroName(key string, site bindSite) string {
	return fmt.Sprintf("TRICE_BIND_DEFINITION_%s_L%d_O%d", key, site.line, site.definitionOrdinal)
}

// bindDefinitionIDMacroName identifies the numeric descriptor consumed by
// counter-selected references to a wrapper definition site.
func bindDefinitionIDMacroName(key string, site bindSite) string {
	return fmt.Sprintf("TRICE_BIND_ID_DEFINITION_%s_L%d_O%d", key, site.line, site.definitionOrdinal)
}

// bindLocationMacroName preserves remigration metadata for direct rebase sites.
func bindLocationMacroName(key string, site bindSite) string {
	return fmt.Sprintf("TRICE_BIND_LOCATION_%s_L%d_O%d", key, site.line, site.sourceOrdinal)
}

// bindLocationIDMacroName identifies the numeric descriptor consumed by a
// direct counter-selected source location.
func bindLocationIDMacroName(key string, site bindSite) string {
	return fmt.Sprintf("TRICE_BIND_ID_LOCATION_%s_L%d_O%d", key, site.line, site.sourceOrdinal)
}

// bindReferenceTID uses definition descriptors for wrappers and literal TIDs for direct sites.
func bindReferenceTID(plans []bindFilePlan, ref bindSiteReference) string {
	site := plans[ref.plan].sites[ref.site]
	if site.definitionName != "" {
		return bindDefinitionMacroName(plans[ref.plan].key, site)
	}
	return bindSiteTID(site)
}

// bindReferenceIDMacro resolves a rebase expansion to one generated numeric
// descriptor. A missing or stale descriptor is therefore a compiler error.
func bindReferenceIDMacro(plans []bindFilePlan, ref bindSiteReference) string {
	site := plans[ref.plan].sites[ref.site]
	if site.definitionName != "" {
		return bindDefinitionIDMacroName(plans[ref.plan].key, site)
	}
	return bindLocationIDMacroName(plans[ref.plan].key, site)
}

// renderBindRebaseModes emits the BEGIN/END behavior only for files that own
// at least one counter-selected source region.
func renderBindRebaseModes(builder *strings.Builder, plan *bindFilePlan) {
	builder.WriteString("#if defined(TRICE_BIND_REBASE_BEGIN)\n")
	builder.WriteString("#if !defined(TRICE_BIND_TARGET_ACTIVE)\n")
	builder.WriteString("// Trice target dispatch is disabled by TRICE_CLEAN or TRICE_OFF.\n")
	builder.WriteString("#elif !defined(__COUNTER__)\n")
	builder.WriteString("#error \"trice bind: this advanced source construct requires __COUNTER__; normal bind sites are unaffected; use trice insert/clean, split Trice calls onto separate lines, or replace the wrapper with a normal/static inline function\"\n")
	builder.WriteString("#elif !defined(TRICE_BIND_REBASE_SCOPE)\n")
	builder.WriteString("#error \"trice bind: generated rebase BEGIN has no scope descriptor\"\n")
	builder.WriteString("#elif defined(TRICE_BIND_REBASE_ACTIVE)\n")
	builder.WriteString("#error \"trice bind: nested generated rebase scopes are not supported\"\n")
	builder.WriteString("#else\n")
	builder.WriteString("enum { TRICE_BIND_REBASE_BASE_NAME(TRICE_BIND_REBASE_SCOPE) = __COUNTER__ };\n")
	builder.WriteString("#define TRICE_BIND_REBASE_ACTIVE 1\n")
	builder.WriteString("#define TRICE_BIND_REBASE_ACTIVE_BASE TRICE_BIND_REBASE_BASE_NAME(TRICE_BIND_REBASE_SCOPE)\n")
	builder.WriteString("#define TRICE_BIND_REBASE_ACTIVE_COUNT TRICE_BIND_REBASE_COUNT_NAME(TRICE_BIND_REBASE_SCOPE)\n")
	builder.WriteString("#define TRICE_BIND_REBASE_ACTIVE_AUTO_APPLY(constructor, implementation, index, ...) TRICE_BIND_REBASE_CAT(TRICE_BIND_REBASE_AUTO_APPLY_, TRICE_BIND_REBASE_SCOPE)(constructor, implementation, index, __VA_ARGS__)\n")
	fmt.Fprintf(builder, "#undef TRICE_BIND_ROUTE_%s\n", plan.key)
	fmt.Fprintf(builder, "#define TRICE_BIND_ROUTE_%s REBASE\n", plan.key)
	builder.WriteString("#endif\n\n")
	builder.WriteString("#elif defined(TRICE_BIND_REBASE_END)\n")
	builder.WriteString("#if !defined(TRICE_BIND_TARGET_ACTIVE)\n")
	builder.WriteString("#undef TRICE_BIND_REBASE_SCOPE\n")
	builder.WriteString("#elif !defined(TRICE_BIND_REBASE_SCOPE) || !defined(TRICE_BIND_REBASE_ACTIVE)\n")
	builder.WriteString("#error \"trice bind: generated rebase END has no matching active BEGIN\"\n")
	builder.WriteString("#else\n")
	builder.WriteString("enum { TRICE_BIND_REBASE_END_NAME(TRICE_BIND_REBASE_SCOPE) = __COUNTER__ };\n")
	builder.WriteString("TRICE_BIND_REBASE_STATIC_ASSERT(TRICE_BIND_REBASE_END_NAME(TRICE_BIND_REBASE_SCOPE) - TRICE_BIND_REBASE_ACTIVE_BASE - 1 == TRICE_BIND_REBASE_ACTIVE_COUNT, TRICE_BIND_REBASE_ASSERT_NAME(TRICE_BIND_REBASE_SCOPE));\n")
	fmt.Fprintf(builder, "#undef TRICE_BIND_ROUTE_%s\n", plan.key)
	fmt.Fprintf(builder, "#define TRICE_BIND_ROUTE_%s BIND\n", plan.key)
	builder.WriteString("#undef TRICE_BIND_REBASE_ACTIVE_AUTO_APPLY\n")
	builder.WriteString("#undef TRICE_BIND_REBASE_ACTIVE_COUNT\n")
	builder.WriteString("#undef TRICE_BIND_REBASE_ACTIVE_BASE\n")
	builder.WriteString("#undef TRICE_BIND_REBASE_ACTIVE\n")
	builder.WriteString("#undef TRICE_BIND_REBASE_SCOPE\n")
	builder.WriteString("#endif\n\n")
}

// bindSiteMacroName forms the expansion-time lookup key used by TRICE_BIND_SITE_HERE.
func bindSiteMacroName(key string, line int) string {
	return fmt.Sprintf("TRICE_BIND_SITE_%s_L%d", key, line)
}

// bindSiteTID formats the complete readable TID expression stored in the descriptor.
func bindSiteTID(site bindSite) string {
	return fmt.Sprintf("%s(%du)", site.wrapper, site.id)
}

// sortedBindDiagnostics creates stable path, line, and message ordering across parallel analysis.
func sortedBindDiagnostics(diagnostics []bindDiagnostic) []bindDiagnostic {
	result := append([]bindDiagnostic(nil), diagnostics...)
	sort.SliceStable(result, func(i, j int) bool {
		if result[i].path != result[j].path {
			return result[i].path < result[j].path
		}
		if result[i].line != result[j].line {
			return result[i].line < result[j].line
		}
		return result[i].message < result[j].message
	})
	return result
}

// formatBindDiagnostic produces one actionable compiler-style diagnostic line.
func formatBindDiagnostic(diagnostic bindDiagnostic) string {
	if diagnostic.line > 0 {
		return fmt.Sprintf("%s:%d: error: %s", diagnostic.path, diagnostic.line, diagnostic.message)
	}
	if diagnostic.path != "" {
		return fmt.Sprintf("%s: error: %s", diagnostic.path, diagnostic.message)
	}
	return "error: " + diagnostic.message
}
