// SPDX-License-Identifier: MIT

package id

import (
	"fmt"
	"sort"
	"strings"
)

// renderBindSidecar creates one stable, guard-free descriptor header for a physical owner file.
func renderBindSidecar(plan *bindFilePlan) []byte {
	sites := append([]bindSite(nil), plan.sites...)
	sort.SliceStable(sites, func(i, j int) bool {
		if sites[i].line != sites[j].line {
			return sites[i].line < sites[j].line
		}
		return sites[i].column < sites[j].column
	})

	var builder strings.Builder
	fmt.Fprintf(&builder, "/// \\file %s\n", plan.sidecarName)
	builder.WriteString("/// \\brief Generated by trice bind. Do not edit.\n\n")
	builder.WriteString("// TRICE_INSERT_OFF - Trice parser exclusion marker\n\n")
	builder.WriteString("#undef TRICE_BIND_FILE_KEY\n")
	fmt.Fprintf(&builder, "#define TRICE_BIND_FILE_KEY %s\n", plan.key)
	fmt.Fprintf(&builder, "#define TRICE_BIND_ROUTE_%s BIND\n\n", plan.key)
	fmt.Fprintf(&builder, "// -defaultStampSize %d\n", DefaultStampSize)

	nameWidth, modeWidth, tidWidth := 0, 0, 0
	for _, site := range sites {
		name := bindSiteMacroName(plan.key, site.line)
		tid := bindSiteTID(site)
		if len(name) > nameWidth {
			nameWidth = len(name)
		}
		if len(site.mode) > modeWidth {
			modeWidth = len(site.mode)
		}
		if len(tid) > tidWidth {
			tidWidth = len(tid)
		}
	}
	for _, site := range sites {
		fmt.Fprintf(
			&builder,
			"#define %-*s %-*s %-*s // %s\n",
			nameWidth,
			bindSiteMacroName(plan.key, site.line),
			modeWidth+1,
			string(site.mode)+",",
			tidWidth,
			bindSiteTID(site),
			site.comment,
		)
	}
	return []byte(builder.String())
}

// bindSiteMacroName forms the expansion-time lookup key used by TRICE_BIND_SITE_HERE.
func bindSiteMacroName(key string, line int) string {
	return fmt.Sprintf("TRICE_BIND_SITE_%s_L%d", key, line)
}

// bindSiteTID formats the complete readable TID expression stored in the descriptor.
func bindSiteTID(site bindSite) string {
	return fmt.Sprintf("%s(%du)", site.wrapper, site.id)
}

// sortedBindDiagnostics creates stable path, line, and message ordering across parallel analysis.
func sortedBindDiagnostics(diagnostics []bindDiagnostic) []bindDiagnostic {
	result := append([]bindDiagnostic(nil), diagnostics...)
	sort.SliceStable(result, func(i, j int) bool {
		if result[i].path != result[j].path {
			return result[i].path < result[j].path
		}
		if result[i].line != result[j].line {
			return result[i].line < result[j].line
		}
		return result[i].message < result[j].message
	})
	return result
}

// formatBindDiagnostic produces one actionable compiler-style diagnostic line.
func formatBindDiagnostic(diagnostic bindDiagnostic) string {
	if diagnostic.line > 0 {
		return fmt.Sprintf("%s:%d: error: %s", diagnostic.path, diagnostic.line, diagnostic.message)
	}
	if diagnostic.path != "" {
		return fmt.Sprintf("%s: error: %s", diagnostic.path, diagnostic.message)
	}
	return "error: " + diagnostic.message
}
