/*
 * Generated by TASKING Pin Mapper for STM32
 * -----------------------------------------
 * device : STM32F407V(E-G)Tx
 * package: LQFP100
 *
 */
#ifndef STM32_CHIP_CONFIG_H_
#define STM32_CHIP_CONFIG_H_


/* Includes */
#include "stm32f4xx.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_rcc.h"


/* Functions */
extern void pincfg_gpio_init(void);
extern void pincfg_gpiod_init(void);
extern void pincfg_i2c1_init(void);
extern void pincfg_i2s3_init(void);


/* Defines */

/* GPIOD*/
#define PINCFG_GPIOD
#define PINCFG_GPIOD_MASK                         GPIO_Pin_4
#define PINCFG_GPIOD_PORT_CLOCK_ENABLE            RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE)

/* GPIOD: PD4 */
#define PINCFG_PD4
#define PINCFG_PD4_PORT                           GPIOD
#define PINCFG_PD4_PIN                            GPIO_Pin_4
#define PINCFG_PD4_PIN_SOURCE                     GPIO_PinSource4
#define PINCFG_PD4_MODE                           GPIO_Mode_OUT
#define PINCFG_PD4_SPEED                          GPIO_Low_Speed
#define PINCFG_PD4_OTYPE                          GPIO_OType_PP
#define PINCFG_PD4_PUPD                           GPIO_PuPd_NOPULL

/* I2C1*/
#define PINCFG_I2C1
#define PINCFG_I2C1_I2C_I2C

/* I2C1_SCL: PB6 */
#define PINCFG_I2C1_SCL
#define PINCFG_I2C1_SCL_PORT                      GPIOB
#define PINCFG_I2C1_SCL_PIN                       GPIO_Pin_6
#define PINCFG_I2C1_SCL_PIN_SOURCE                GPIO_PinSource6
#define PINCFG_I2C1_SCL_PORT_CLOCK_ENABLE         RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOB, ENABLE)
#define PINCFG_I2C1_SCL_AF                        GPIO_AF_I2C1
#define PINCFG_I2C1_SCL_MODE                      GPIO_Mode_AF
#define PINCFG_I2C1_SCL_SPEED                     GPIO_Fast_Speed
#define PINCFG_I2C1_SCL_OTYPE                     GPIO_OType_OD
#define PINCFG_I2C1_SCL_PUPD                      GPIO_PuPd_NOPULL

/* I2C1_SDA: PB9 */
#define PINCFG_I2C1_SDA
#define PINCFG_I2C1_SDA_PORT                      GPIOB
#define PINCFG_I2C1_SDA_PIN                       GPIO_Pin_9
#define PINCFG_I2C1_SDA_PIN_SOURCE                GPIO_PinSource9
#define PINCFG_I2C1_SDA_PORT_CLOCK_ENABLE         RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOB, ENABLE)
#define PINCFG_I2C1_SDA_AF                        GPIO_AF_I2C1
#define PINCFG_I2C1_SDA_MODE                      GPIO_Mode_AF
#define PINCFG_I2C1_SDA_SPEED                     GPIO_Fast_Speed
#define PINCFG_I2C1_SDA_OTYPE                     GPIO_OType_OD
#define PINCFG_I2C1_SDA_PUPD                      GPIO_PuPd_NOPULL

/* I2S3*/
#define PINCFG_I2S3
#define PINCFG_I2S3_MASTER_CLOCK_ENABLED
#define PINCFG_I2S3_MODE_HALF_DUPLEX_MASTER

/* I2S3_CK: PC10 */
#define PINCFG_I2S3_CK
#define PINCFG_I2S3_CK_PORT                       GPIOC
#define PINCFG_I2S3_CK_PIN                        GPIO_Pin_10
#define PINCFG_I2S3_CK_PIN_SOURCE                 GPIO_PinSource10
#define PINCFG_I2S3_CK_PORT_CLOCK_ENABLE          RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOC, ENABLE)
#define PINCFG_I2S3_CK_AF                         GPIO_AF_SPI3
#define PINCFG_I2S3_CK_MODE                       GPIO_Mode_AF
#define PINCFG_I2S3_CK_SPEED                      GPIO_Fast_Speed
#define PINCFG_I2S3_CK_OTYPE                      GPIO_OType_PP
#define PINCFG_I2S3_CK_PUPD                       GPIO_PuPd_NOPULL

/* I2S3_MCK: PC7 */
#define PINCFG_I2S3_MCK
#define PINCFG_I2S3_MCK_PORT                      GPIOC
#define PINCFG_I2S3_MCK_PIN                       GPIO_Pin_7
#define PINCFG_I2S3_MCK_PIN_SOURCE                GPIO_PinSource7
#define PINCFG_I2S3_MCK_PORT_CLOCK_ENABLE         RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOC, ENABLE)
#define PINCFG_I2S3_MCK_AF                        GPIO_AF_SPI3
#define PINCFG_I2S3_MCK_MODE                      GPIO_Mode_AF
#define PINCFG_I2S3_MCK_SPEED                     GPIO_Fast_Speed
#define PINCFG_I2S3_MCK_OTYPE                     GPIO_OType_PP
#define PINCFG_I2S3_MCK_PUPD                      GPIO_PuPd_NOPULL

/* I2S3_SD: PC12 */
#define PINCFG_I2S3_SD
#define PINCFG_I2S3_SD_PORT                       GPIOC
#define PINCFG_I2S3_SD_PIN                        GPIO_Pin_12
#define PINCFG_I2S3_SD_PIN_SOURCE                 GPIO_PinSource12
#define PINCFG_I2S3_SD_PORT_CLOCK_ENABLE          RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOC, ENABLE)
#define PINCFG_I2S3_SD_AF                         GPIO_AF_SPI3
#define PINCFG_I2S3_SD_MODE                       GPIO_Mode_AF
#define PINCFG_I2S3_SD_SPEED                      GPIO_Fast_Speed
#define PINCFG_I2S3_SD_OTYPE                      GPIO_OType_PP
#define PINCFG_I2S3_SD_PUPD                       GPIO_PuPd_NOPULL

/* I2S3_WS: PA4 */
#define PINCFG_I2S3_WS
#define PINCFG_I2S3_WS_PORT                       GPIOA
#define PINCFG_I2S3_WS_PIN                        GPIO_Pin_4
#define PINCFG_I2S3_WS_PIN_SOURCE                 GPIO_PinSource4
#define PINCFG_I2S3_WS_PORT_CLOCK_ENABLE          RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE)
#define PINCFG_I2S3_WS_AF                         GPIO_AF_SPI3
#define PINCFG_I2S3_WS_MODE                       GPIO_Mode_AF
#define PINCFG_I2S3_WS_SPEED                      GPIO_Fast_Speed
#define PINCFG_I2S3_WS_OTYPE                      GPIO_OType_PP
#define PINCFG_I2S3_WS_PUPD                       GPIO_PuPd_NOPULL


#endif /* STM32_CHIP_CONFIG_H_ */
