/*! \file triceOff.h
\author thomas.hoehenleitner [at] seerose.net
*******************************************************************************/

// global function prototypes: (not all always used)

#define TriceInitRingBufferMargins()
#define WatchRingBufferMargins()
#define TriceDiagnostics(index) TRICE_UNUSED(index)
#define TriceNonBlockingWriteUartA(buf, nByte) TRICE_UNUSED(buf) TRICE_UNUSED(nByte)
#define TriceNonBlockingWriteUartB(buf, nByte) TRICE_UNUSED(buf) TRICE_UNUSED(nByte)
#define TriceNonBlockingDirectWrite(triceStart, wordCount) TRICE_UNUSED(triceStart) TRICE_UNUSED(wordCount)
#define TriceNonBlockingDirectWrite8Auxiliary(enc, encLen) TRICE_UNUSED(enc) TRICE_UNUSED(encLen)
#define TriceNonBlockingDeferredWrite8Auxiliary(enc, encLen) TRICE_UNUSED(enc) TRICE_UNUSED(encLen)
#define TriceNonBlockingDirectWrite32Auxiliary(enc, count) TRICE_UNUSED(enc) TRICE_UNUSED(encLen)
//#define TriceNonBlockingDeferredWrite32Auxiliary(enc, count) TRICE_UNUSED(enc) TRICE_UNUSED(encLen)
#define TriceInit()
#define TriceLogDiagnosticData()
#define TriceLogSeggerDiagnostics()
#define TriceNonBlockingDeferredWrite8(ticeID, enc, encLen) TRICE_UNUSED(ticeID) TRICE_UNUSED(enc) TRICE_UNUSED(encLen)
#define TriceTransfer()
#define triceDataLen(p)
#define TriceEnoughSpace()
#define TriceOutDepth()
#define TriceDepth()
#define TriceDepthMax()
#define TriceEncode(encrypt, framing, dst, buf, len) TRICE_UNUSED(encrypt) TRICE_UNUSED(framing) TRICE_UNUSED(dst) TRICE_UNUSED(len)
#define TriceWriteDeviceCgo(buf, len) TRICE_UNUSED(buf) TRICE_UNUSED(len) //!< TriceWriteDeviceCgo is only needed for testing C-sources from Go.

#define TriceBlockingWriteUartA(buf, len) TRICE_UNUSED(buf) TRICE_UNUSED(len)
#define triceServeTransmitUartA()
#define triceTriggerTransmitUartA()
#define TriceOutDepthUartA()

#define TriceBlockingWriteUartB(buf, len) TRICE_UNUSED(buf) TRICE_UNUSED(len)
#define triceServeTransmitUartB()
#define triceTriggerTransmitUartB()
#define TriceOutDepthUartB()

#define XTEAEncrypt(p, n) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define XTEADecrypt(p, n) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define XTEAInitTable()

#define TRICE_XTEA_H_ // do not include xtea.h
#define COBS_H_       // do not include cobs.h
#define TCOBS_H_      // do not include tcobs.h
#define SEGGER_RTT_H  // do not include SEGGER_RTT.h

// Trice functions and macros

#define id(n) (n)
#define Id(n) (n)
#define ID(n) (n)
#define iD(n) (n)

#define TRICE_ENTER
#define TRICE_LEAVE
#define TRICE_PUT(n) TRICE_UNUSED(n)
#define TRICE_PUT16(n) TRICE_UNUSED(n)
#define TRICE_PUT16_1616(x, n)
#define PUT_BUFFER(p, n) TRICE_UNUSED(p) TRICE_UNUSED(n)

#define TRICE0(...)
#define trice0(...)
#define Trice0(...)
#define TRice0(...)

#define triceAssertTrue(...)
#define TriceAssertTrue(...)
#define TRiceAssertTrue(...)
#define triceAssertFalse(...)
#define TriceAssertFalse(...)
#define TRiceAssertFalse(...)

#define triceAssertFail(...)
#define TriceAssertFail(...)
#define TRiceAssertFail(...)

#define triceAssert(...)
#define TriceAssert(...)
#define TRiceAssert(...)

#define triceAssertOrReturn(msg, flag) do {if (!(flag)) {return;}} while(0)
#define TriceAssertOrReturn(msg, flag) do {if (!(flag)) {return;}} while(0)
#define TRiceAssertOrReturn(msg, flag) do {if (!(flag)) {return;}} while(0)

#define triceAssertOrReturnValue(msg, flag, value) do {if (!(flag)) {return (value);}} while(0)
#define TriceAssertOrReturnValue(msg, flag, value) do {if (!(flag)) {return (value);}} while(0)
#define TRiceAssertOrReturnValue(msg, flag, value) do {if (!(flag)) {return (value);}} while(0)

// All following macros are defined without ID and as variadic, to avoid editor warnings for TRICE_CLEAN == 1 or TRICE_OFF == 1

#define TRICE_S(p, s, ...) TRICE_UNUSED(p) TRICE_UNUSED(s)
#define triceS(p, s, ...) TRICE_UNUSED(p) TRICE_UNUSED(s)
#define TriceS(p, s, ...) TRICE_UNUSED(p) TRICE_UNUSED(s)
#define TRiceS(p, s, ...) TRICE_UNUSED(p) TRICE_UNUSED(s)

#define TRICE_N(p, s, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(s) TRICE_UNUSED(n)
#define triceN(p, s, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(s) TRICE_UNUSED(n)
#define TriceN(p, s, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(s) TRICE_UNUSED(n)
#define TRiceN(p, s, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(s) TRICE_UNUSED(n)

// #define TRICE_B(iD, ...)
#define triceB(p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TriceB(p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TRiceB(p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)

// #define TRICE_F(iD, ...)
#define triceF(p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TriceF(p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TRiceF(p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)

#define TRICE(...)
#define trice(...)
#define Trice(...)
#define TRice(...)
#define TRICE8(...)
#define trice8(...)
#define Trice8(...)
#define TRice8(...)
#define TRICE16(...)
#define trice16(...)
#define Trice16(...)
#define TRice16(...)
#define TRICE32(...)
#define trice32(...)
#define Trice32(...)
#define TRice32(...)
#define TRICE64(...)
#define trice64(...)
#define Trice64(...)
#define TRice64(...)

#define TRICE_0(...)
#define TRICE_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define TRICE_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define TRICE_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define TRICE_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define TRICE_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define TRICE_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define TRICE_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define TRICE_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define TRICE_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define TRICE_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define TRICE_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define TRICE_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define trice_0(...)
#define trice_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define trice_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define trice_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define trice_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define trice_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define trice_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define trice_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define trice_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define trice_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define trice_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define trice_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define trice_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define Trice_0(...)
#define Trice_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define Trice_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define Trice_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define Trice_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define Trice_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define Trice_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define Trice_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define Trice_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define Trice_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define Trice_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define Trice_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define Trice_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define TRice_0(...)
#define TRice_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define TRice_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define TRice_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define TRice_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define TRice_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define TRice_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define TRice_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define TRice_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define TRice_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define TRice_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define TRice_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define TRice_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)

#define TRICE8_B(id, fmt, p, n) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define trice8B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define Trice8B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TRice8B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TRICE8_F(id, fmt, p, n) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define trice8F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define Trice8F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TRice8F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)

#define TRICE8_0(...)
#define TRICE8_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define TRICE8_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define TRICE8_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define TRICE8_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define TRICE8_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define TRICE8_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define TRICE8_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define TRICE8_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define TRICE8_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define TRICE8_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define TRICE8_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define TRICE8_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define trice8_0(...)
#define trice8_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define trice8_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define trice8_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define trice8_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define trice8_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define trice8_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define trice8_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define trice8_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define trice8_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define trice8_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define trice8_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define trice8_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define Trice8_0(...)
#define Trice8_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define Trice8_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define Trice8_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define Trice8_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define Trice8_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define Trice8_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define Trice8_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define Trice8_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define Trice8_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define Trice8_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define Trice8_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define Trice8_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define TRice8_0(...)
#define TRice8_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define TRice8_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define TRice8_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define TRice8_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define TRice8_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define TRice8_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define TRice8_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define TRice8_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define TRice8_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define TRice8_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define TRice8_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define TRice8_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)

#define TRICE16_B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define trice16B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define Trice16B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TRice16B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TRICE16_F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define trice16F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define Trice16F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TRice16F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)

#define TRICE16_0(...)
#define TRICE16_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define TRICE16_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define TRICE16_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define TRICE16_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define TRICE16_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define TRICE16_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define TRICE16_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define TRICE16_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define TRICE16_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define TRICE16_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define TRICE16_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define TRICE16_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define trice16_0(...)
#define trice16_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define trice16_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define trice16_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define trice16_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define trice16_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define trice16_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define trice16_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define trice16_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define trice16_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define trice16_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define trice16_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define trice16_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define Trice16_0(...)
#define Trice16_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define Trice16_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define Trice16_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define Trice16_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define Trice16_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define Trice16_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define Trice16_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define Trice16_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define Trice16_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define Trice16_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define Trice16_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define Trice16_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define TRice16_0(...)
#define TRice16_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define TRice16_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define TRice16_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define TRice16_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define TRice16_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define TRice16_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define TRice16_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define TRice16_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define TRice16_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define TRice16_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define TRice16_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define TRice16_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)

#define TRICE32_B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define trice32B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define Trice32B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TRice32B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TRICE32_F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define trice32F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define Trice32F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TRice32F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)

#define TRICE32_0(...)
#define TRICE32_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define TRICE32_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define TRICE32_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define TRICE32_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define TRICE32_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define TRICE32_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define TRICE32_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define TRICE32_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define TRICE32_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define TRICE32_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define TRICE32_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define TRICE32_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define trice32_0(...)
#define trice32_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define trice32_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define trice32_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define trice32_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define trice32_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define trice32_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define trice32_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define trice32_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define trice32_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define trice32_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define trice32_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define trice32_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define Trice32_0(...)
#define Trice32_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define Trice32_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define Trice32_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define Trice32_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define Trice32_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define Trice32_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define Trice32_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define Trice32_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define Trice32_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define Trice32_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define Trice32_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define Trice32_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define TRice32_0(...)
#define TRice32_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define TRice32_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define TRice32_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define TRice32_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define TRice32_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define TRice32_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define TRice32_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define TRice32_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define TRice32_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define TRice32_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define TRice32_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define TRice32_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)

#define TRICE64_B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define trice64B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define Trice64B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TRice64B(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TRICE64_F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define trice64F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define Trice64F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)
#define TRice64F(fmt, p, n, ...) TRICE_UNUSED(p) TRICE_UNUSED(n)

#define TRICE64_0(...)
#define TRICE64_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define TRICE64_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define TRICE64_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define TRICE64_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define TRICE64_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define TRICE64_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define TRICE64_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define TRICE64_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define TRICE64_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define TRICE64_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define TRICE64_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define TRICE64_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define trice64_0(...)
#define trice64_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define trice64_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define trice64_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define trice64_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define trice64_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define trice64_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define trice64_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define trice64_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define trice64_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define trice64_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define trice64_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define trice64_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define Trice64_0(...)
#define Trice64_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define Trice64_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define Trice64_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define Trice64_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define Trice64_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define Trice64_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define Trice64_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define Trice64_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define Trice64_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define Trice64_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define Trice64_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define Trice64_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
#define TRice64_0(...)
#define TRice64_1(fmt, v0, ...) TRICE_UNUSED(v0)
#define TRice64_2(fmt, v0, v1, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1)
#define TRice64_3(fmt, v0, v1, v2, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2)
#define TRice64_4(fmt, v0, v1, v2, v3, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3)
#define TRice64_5(fmt, v0, v1, v2, v3, v4, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4)
#define TRice64_6(fmt, v0, v1, v2, v3, v4, v5, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5)
#define TRice64_7(fmt, v0, v1, v2, v3, v4, v5, v6, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6)
#define TRice64_8(fmt, v0, v1, v2, v3, v4, v5, v6, v7, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7)
#define TRice64_9(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8)
#define TRice64_10(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9)
#define TRice64_11(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10)
#define TRice64_12(fmt, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, ...) TRICE_UNUSED(v0) TRICE_UNUSED(v1) TRICE_UNUSED(v2) TRICE_UNUSED(v3) TRICE_UNUSED(v4) TRICE_UNUSED(v5) TRICE_UNUSED(v6) TRICE_UNUSED(v7) TRICE_UNUSED(v8) TRICE_UNUSED(v9) TRICE_UNUSED(v10) TRICE_UNUSED(v11)
// clang-format on
