// SPDX-License-Identifier: MIT
//! \file triceConfig.h

#ifndef TRICE_CONFIG_H_
#define TRICE_CONFIG_H_

#ifdef __cplusplus
extern "C" {
#endif

#define TRICE_LEGACY_RPC_SUPPORT 1
#define TRICE_ABC_TRANSMIT_SUPPORT 1
#define TRICE_TRANSFER_ORDER_IS_BIG_ENDIAN 1
#define TRICE_BUFFER TRICE_STATIC_BUFFER
#define TRICE_DIRECT_OUTPUT 1
#define TRICE_DIRECT_XTEA_ENCRYPT 1
#define TRICE_DIRECT_OUT_FRAMING TRICE_FRAMING_COBS
#define TRICE_DIRECT_SEGGER_RTT_32BIT_WRITE 1
#define TRICE_CGO 1
#define TRICE_X0_COUNTED_BUFFER_SUPPORT 1
#define TRICE_CYCLE_COUNTER 0

#ifdef __cplusplus
}
#endif

#endif /* TRICE_CONFIG_H_ */
